function art = run_compare(seg_in, opts)
%RUN_COMPARE  Compare stage runner: mmacos engine vs the linear model, per DOF.
%
%   art = run_compare(SEG_IN, 'hx', HX, 'jac', JAC, 'met', METMAT) is
%   the compare stage of the design pipeline
%       design -> segmentation -> sensitivities -> MET -> COMPARE -> simulate
%   (see design/runners/README.md).  It pokes each DOF of the linear
%   model IN TURN — first the rigid-body x DOFs of the sensed bodies
%   (default 100 nrad / 100 nm), then the z figure DOFs (segment-local
%   MonZernike modes), then the grid DOFs (per-segment influence
%   pokes) — and, for every poke, displays TWO graphics side by side:
%   one from the mmacos ENGINE, one from the LINEAR MODEL, each
%   showing the center-field OPD change on top of stacked bar charts
%   of the metrology beam lengths l and the edge-sensor readings by
%   axis (e_piston / e_gap / e_shear).  The z and grid DOFs do not
%   move l or e (met points and sensor points ride the rigid frames,
%   not the figure) — their bar charts stay in the movie, reading
%   zero, engine and model alike (Dave 2026-07-19).  Each poke stays
%   on screen for a settable dwell; every frame is saved and the
%   sequence is assembled into a GIF, alongside a per-poke agreement
%   report.
%
%   The linear model (Dave 2026-07-19, verbatim intent + the figure-
%   sensing extension of the same day):
%       w = dwdx*x + dwdz*z + dwdgrid*g + dwdu*u + w0
%       m = [l; e] = dmdx*x + dmdz*z + dmdgrid*g + m0
%   dmdz/dmdgrid are generated by macos.design.dmet_dfig (mode shape
%   evaluated at each sensor/launcher mount point, projected on the
%   measurement axis): the l rows and the e PISTON rows carry the
%   figure response; gap/shear rows vanish through the normal
%   projection.  The ENGINE's METcalc and the Hx keep met/sensor
%   points rigid, so for z/grid pokes the engine-side l/e bars read
%   zero while the LINEAR side shows the dmdz/dmdgrid prediction --
%   the movie displays that model-vs-engine gap explicitly, and the
%   blocks are exported for the simulator stage's estimator H.
%   The linear side of a poke is the matching Jacobian column times
%   the poke; the engine side is the same poke applied through the
%   SAME channel classes the sensitivity harvest used, with a retrace
%   (+ METcalc where the Rx carries met blocks).  u (the control) is
%   the SEGMENT + SM subset of x; the matching dwdx columns are
%   exported as dwdu for the simulator stage.
%
%   Engine-truth channels per poke:
%     w  channel apply (RigidBodyChannel / MonZernChannel /
%        GridChannel — the s4 harvest classes) -> trace(nElt-1) ->
%        OPD; delta vs the unperturbed baseline on the same mask.
%        Grid pokes run on the grid-augmented Rx of the harvest
%        (og.rx_path), with the influence basis REBUILT by the same
%        macos.segment_grid_basis call — a basis mismatch would fail
%        the agreement gate.
%     l  macos.met() (met points ride their element under the
%        programmatic perturb path); zero rows where the loaded Rx
%        declares no metrology (the grid-augmented Rx).
%     e  finite-rotation kinematics at the SegMirMaker sensor points
%        (Hx SensorPos): the sensor axis and moment arm ARE the
%        measurement model, so truth = axis . ((R(theta)-I)*rho +
%        delta) with the FULL rotation matrix — first order
%        reproduces the dedx row, the difference is the genuine
%        linearization error.  dedx is REBUILT from the Hx sidecar
%        (the met .mat copy is only cross-checked — a regenerated Hx
%        would otherwise poison the comparison).
%
%   REQUIRED OPTIONS:
%     'hx'    SegMirMaker Hx.m sidecar (axis/loc/SensorPos form)
%     'jac'   sensitivities .mat (s4_jacobians.mat: ox + optional
%             oz/og) or the dw_dx_multi 'ox' struct — must carry
%             per_field blocks
%     'met'   MET-stage .mat (run_met output) or an equivalent struct:
%             dldx (+ dldx_opt), bodies, seg, met_in / metopt_in
%   OPTIONS:
%     'channels'   subset of ["x" "z" "grid"] (default: every channel
%                  the jac provides, in that order — Dave 2026-07-19)
%     'met_rx'     Rx to poke for x/z (default: the met struct's
%                  metopt_in if present, else met_in; matching dldx)
%     'grid_rx'    Rx for the grid pokes (default: og.rx_path — the
%                  grid-augmented Rx the harvest used)
%     'poke_rot'   rotation poke, rad (default 1e-7 = 100 nrad)
%     'poke_trans' translation poke, m (default 1e-7 = 100 nm)
%     'poke_fig'   figure poke: MonZernike / influence amplitude
%                  (default 1e-7 = 100 nm surface)
%     'dofs'       x-DOF subset 1..6 = [Rx Ry Rz Tx Ty Tz] (default all)
%     'bodies'     x body subset (indices into the met bodies list,
%                  default all)
%     'control'    control-body indices for the dwdu export (default
%                  segments + hub — "segment and SM x", Dave)
%     'pm_ref_elt' segment_grid_basis footprint target for the grid
%                  basis rebuild (default 1 — the run_sensitivities
%                  default; must match the harvest)
%     'dwell'      seconds each poke stays on screen and per GIF frame
%                  (default 1.6 — Dave 2026-07-19, 0.25 read too fast)
%     'w_floor'    null-response floor, m (default 1e-12): pokes with
%                  no physical w (or l) response report rel = NaN
%                  ('null') instead of an FD-noise ratio
%     'gif'        assemble <name>_compare.gif (default true)
%     'ngridpts'   ray-grid override — MUST match the jac harvest
%                  sampling (default [] = keep the .in values)
%     'model_size' engine model (default 512)
%     'out_dir'    artifact directory (default: beside SEG_IN)
%     'name'       artifact basename (default: SEG_IN's basename)
%     'visible'    show the two figures live (default true; the movie
%                  IS the point — pass false in batch/tests)
%     'verbose'    (default true)
%
%   art: .table (per-poke agreement metrics, .chan = x|z|grid),
%        .frames_dir, .gif, .report, .mat, .dwdu, .u_cols, .worst.
%
%   See also: run_met, run_sensitivities, macos.design.edge_sensors,
%             macos.channels.RigidBodyChannel, macos.channels.
%             MonZernChannel, macos.channels.grid_channels.

arguments
    seg_in (1,1) string
    opts.hx (1,1) string
    opts.jac
    opts.met
    opts.channels (1,:) string = "auto"
    opts.met_rx (1,1) string = ""
    opts.grid_rx (1,1) string = ""
    opts.poke_rot (1,1) double {mustBePositive} = 1e-7
    opts.poke_trans (1,1) double {mustBePositive} = 1e-7
    opts.poke_fig (1,1) double {mustBePositive} = 1e-7
    opts.dofs (1,:) double {mustBeInteger, mustBeMember(opts.dofs, 1:6)} = 1:6
    opts.bodies double = []
    opts.control double = []
    opts.pm_ref_elt (1,1) double {mustBeInteger, mustBePositive} = 1
    opts.dwell (1,1) double {mustBeNonnegative} = 1.6
    opts.w_floor (1,1) double {mustBePositive} = 1e-12
    opts.gif (1,1) logical = true
    opts.ngridpts double = []
    opts.model_size (1,1) double = 512
    opts.out_dir (1,1) string = ""
    opts.name (1,1) string = ""
    opts.visible (1,1) logical = true
    opts.verbose (1,1) logical = true
end
assert(isfile(seg_in), 'run_compare: %s not found', seg_in);
assert(isfile(opts.hx), 'run_compare: Hx sidecar %s not found', opts.hx);
[ind, base] = fileparts(seg_in);
out_dir = opts.out_dir;  if strlength(out_dir) == 0, out_dir = ind; end
name = opts.name;        if strlength(name) == 0,   name = base; end
pth = @(suffix) char(fullfile(out_dir, name + suffix));
log_ = fopen(pth("_compare_report.txt"), 'w');
closer = onCleanup(@() fclose(log_));
if opts.verbose
    say = @(varargin) fprintf(1, varargin{:}) + fprintf(log_, varargin{:});
else
    say = @(varargin) fprintf(log_, varargin{:});
end
say('==== run_compare: %s ====\n', seg_in);

%% -- [0] ingest the upstream artifacts --------------------------------
M = met_struct_(opts.met);
seg = M.seg;  nseg = seg.nseg;  bodies = M.bodies;  nb = numel(bodies);
assert(isequal(bodies(1:nseg), seg.seg_elts), ...
    'run_compare: met bodies do not lead with the segment elements');
met_rx = opts.met_rx;
dldx = M.dldx;
if strlength(met_rx) == 0
    if isfield(M, 'metopt_in') && strlength(string(M.metopt_in)) > 0 ...
            && isfile(M.metopt_in)
        met_rx = string(M.metopt_in);
        if isfield(M, 'dldx_opt') && ~isempty(M.dldx_opt)
            dldx = M.dldx_opt;
        end
    else
        met_rx = string(M.met_in);
    end
end
assert(isfile(met_rx), 'run_compare: met Rx %s not found', met_rx);
nl = size(dldx, 1);
J = jac_all_(opts.jac);
ox = J.ox;
chansel = opts.channels;
if isscalar(chansel) && chansel == "auto"
    chansel = "x";
    if ~isempty(J.oz), chansel(end+1) = "z"; end
    if ~isempty(J.og), chansel(end+1) = "grid"; end
end
assert(~any(chansel == "z")    || ~isempty(J.oz), 'run_compare: jac has no dwdz output');
assert(~any(chansel == "grid") || ~isempty(J.og), 'run_compare: jac has no dwdgrid output');
% Convention match: the dwdx leg must share the per-field exit-pupil
% reset convention with the dwdz/dwdgrid legs it is joined with.  Mixing
% a frozen-EP dwdx (reset_xp=false) into a model whose dwdz/dwdgrid used
% reset_xp=true silently mixes tilt-reference conventions across channels
% (the family-asymmetry hazard the reset_xp addition closes).  The stamp
% is true | false | 'no-effect' -- 'no-effect' (FEX found no pupil to
% write, so the harvest is frozen-EP in practice) is EFFECTIVELY frozen,
% so it matches a false leg; only a genuine true-vs-false split is a
% mismatch.  reset_eff_() maps the tri-state stamp to that effective bool.
if isfield(ox, 'reset_xp')
    for leg = {J.oz, J.og}
        L = leg{1};
        if ~isempty(L) && isfield(L, 'reset_xp')
            assert(reset_eff_(ox.reset_xp) == reset_eff_(L.reset_xp), ...
                'run_compare:reset_xp_mismatch', ...
                ['dwdx reset_xp=%s but a dwdz/dwdgrid leg used reset_xp=%s' ...
                 ' -- regenerate the Jacobian with one convention'], ...
                reset_str_(ox.reset_xp), reset_str_(L.reset_xp));
        end
    end
end
icf = find(strcmp(ox.field_names, 'C'), 1);
assert(~isempty(icf), 'run_compare: jac has no center field ''C''');
% center-field dwdx block for the sensed bodies, [rot|trans] col order
[Bc, colmap, nochan] = dwdx_cols_(ox.per_field_dwdx{icf}, ...
    ox.channel_names, bodies);
W0j = ox.per_field_w_nom_2d{icf};
[~, jndx] = macos.m2v(W0j);
es = macos.design.edge_sensors(opts.hx);
assert(any(es.axis > 0), ['run_compare: legacy Hx (no MeasAxis/' ...
    'SensorPos) -- regenerate with the 2026-07-19 SegMirMaker']);
ie_p = find(es.axis == 1);  ie_g = find(es.axis == 2);
ie_s = find(es.axis == 3);
% dedx from the CURRENT Hx sidecar (readings BaseUnits -> SI: rot cols
% x cbm, translation cols dimensionless -- same construction as
% run_met).  The met .mat's copy is only cross-checked: if the Hx was
% regenerated after the MET stage ran, the stale rows would poison the
% comparison (caught 2026-07-19: the gap/shear axis-relabel left the
% s5 .mat one Hx generation behind).
dedx = zeros(es.nmeas, 6*nb);
dedx(:, 1:6*nseg) = es.dedx;                  % SI-scaled once cbm known
say(['[0] %d bodies (%d segments), channels [%s]; met Rx %s\n' ...
     '    jac: center field %d x %d x-cols; dedx %dx%d; dldx %dx%d\n'], ...
    nb, nseg, strjoin(chansel, ' '), met_rx, size(Bc, 1), size(Bc, 2), ...
    size(dedx), size(dldx));
if ~isempty(nochan)
    say(['    NOTE: no dwdx channels for element(s) %s (Reference/' ...
         'FocalPlane-class body):\n    linear w = 0 for their pokes ' ...
         '(engine response is null there too -- l/e still compared)\n'], ...
        num2str(nochan));
end

% x poke set
bsel = opts.bodies;  if isempty(bsel), bsel = 1:nb; end
control = opts.control;
if isempty(control), control = 1:min(nseg+1, nb); end   % segments + SM/hub
DOFN = {'Rx', 'Ry', 'Rz', 'Tx', 'Ty', 'Tz'};

%% -- [1] engine baseline ----------------------------------------------
old = cd(out_dir);  restore = onCleanup(@() cd(old));
m = macos.Session(opts.model_size);
m.load_rx(char(met_rx));
if ~isempty(opts.ngridpts), m.set_src_sampling(opts.ngridpts); end
cbm = m.cbm();
for s = 1:nseg
    dedx(:, (s-1)*6+(1:3)) = dedx(:, (s-1)*6+(1:3)) * cbm;
end
if isfield(M, 'dedx') && isequal(size(M.dedx), size(dedx)) ...
        && max(abs(dedx(:) - M.dedx(:))) > 1e-9 * max(abs(dedx(:)))
    warning('run_compare:stale_dedx', ...
        ['the met .mat''s dedx does not match the Hx sidecar -- the Hx ' ...
         'was regenerated after the MET stage ran; using the Hx (rerun ' ...
         'the MET stage to refresh its estimator products)']);
    say('    WARNING: met .mat dedx is STALE vs the Hx sidecar (using the Hx)\n');
end
wf_elt = m.num_elt() - 1;
m.trace(wf_elt);
Wb = m.opd();                                 % phase baseline (met Rx)
assert(isequal(size(Wb), size(W0j)), ['run_compare: engine OPD canvas ' ...
    '%dx%d vs jac %dx%d -- ngridpts must match the jac harvest'], ...
    size(Wb, 1), size(Wb, 2), size(W0j, 1), size(W0j, 2));
maskb = Wb ~= 0;
nover = nnz(maskb & (W0j == 0)) + nnz(~maskb & (W0j ~= 0));
l0 = macos.met();
assert(l0.n == nl, ...
    'run_compare: engine declares %d met beams, dldx has %d rows', l0.n, nl);
l0b = l0.l;
say('    baseline: %d OPD pixels (jac mask mismatch %d px), %d met beams, %d edge rows\n', ...
    nnz(maskb), nover, l0.n, es.nmeas);

%% -- [2] the poke loop: x, then z, then grid --------------------------
fdir = pth("_frames");
if ~exist(fdir, 'dir'), mkdir(fdir); end
gif_file = '';
if opts.gif, gif_file = pth("_compare.gif"); end
vis = 'off';  if opts.visible, vis = 'on'; end
fe = figure('Visible', vis, 'Position', [40 60 640 940], 'Color', 'w');
fl = figure('Visible', vis, 'Position', [700 60 640 940], 'Color', 'w');
fig_closer = onCleanup(@() close([fe fl]));
T = struct('chan', {}, 'label', {}, 'body', {}, 'dof', {}, 'poke', {}, ...
    'w_rms_t', {}, 'w_rel', {}, 'l_max_t', {}, 'l_rel', {}, ...
    'e_max_t', {}, 'e_rel', {}, 'l_max_m', {}, 'e_max_m', {});
ip = 0;

%% x: rigid-body DOFs of the sensed bodies
if any(chansel == "x")
    say('\n[2] x: rigid-body pokes (%g nrad rot / %g nm trans), %d bodies x %d DOFs:\n', ...
        opts.poke_rot*1e9, opts.poke_trans*1e9, numel(bsel), numel(opts.dofs));
    for kb = bsel(:).'
        for d = opts.dofs(:).'
            col = (kb-1)*6 + d;
            poke = opts.poke_trans;  utxt = 'nm';
            if d <= 3, poke = opts.poke_rot;  utxt = 'nrad'; end
            lbl = sprintf('%s %s %+g %s', body_name_(kb, nseg, bodies), ...
                          DOFN{d}, poke*1e9, utxt);
            ch = macos.channels.RigidBodyChannel(m, bodies(kb), d - 1);
            th = zeros(3, 1);  dl = zeros(3, 1);
            if d <= 3, th(d) = poke;  else, dl(d-3) = poke; end
            if kb <= nseg
                de_t = e_truth_(es, seg, cbm, kb, th, dl);
            else
                de_t = zeros(es.nmeas, 1);   % edge sensors live on segments
            end
            do_poke_('x', lbl, bodies(kb), d, ch, poke, ...
                col2map_(Bc(:, col)*poke, jndx), dldx(:, col)*poke, ...
                dedx(:, col)*poke, de_t);
        end
    end
end

%% z: segment-figure MonZernike DOFs.  The engine's METcalc holds met
%% points rigid and the Hx has no figure path, so the ENGINE l/e bars
%% read zero; the LINEAR bars show the dmdz model (figure motion at
%% each sensor/launcher mount point -- piston + l rows respond,
%% gap/shear vanish through the normal projection).
gmet = macos.met_geom();                      % on the loaded met Rx
dmz = [];  dmg = [];
if any(chansel == "z")
    oz = J.oz;
    icz = find(strcmp(oz.field_names, 'C'), 1);
    assert(~isempty(icz), 'run_compare: dwdz jac has no center field');
    Bz = oz.per_field_dwdz{icz};
    W0z = oz.per_field_w_nom_2d{icz};
    assert(isequal(size(W0z), size(Wb)), ...
        'run_compare: dwdz canvas %dx%d vs engine %dx%d', ...
        size(W0z, 1), size(W0z, 2), size(Wb, 1), size(Wb, 2));
    [~, jnz] = macos.m2v(W0z);
    dmz = macos.design.dmet_dfig(seg, es, gmet, ...
        'z_names', oz.channel_names, 'unit_to_m', cbm);
    say(['\n[2z] z: segment MonZernike pokes (%g nm figure), %d modes;\n' ...
         '     linear l/e = dmdz (dmet_dfig at the mount points) -- the\n' ...
         '     engine METcalc/Hx are RIGID, their bars read zero\n'], ...
        opts.poke_fig*1e9, numel(oz.channel_names));
    for k = 1:numel(oz.channel_names)
        tok = regexp(oz.channel_names{k}, ...
            '^Elt (\d+) MonZern(\d+)$', 'tokens', 'once');
        assert(~isempty(tok), ...
            'run_compare: unexpected dwdz channel ''%s'' (monzern expected)', ...
            oz.channel_names{k});
        elt = str2double(tok{1});  mode = str2double(tok{2});
        lbl = sprintf('%s Z%d %+g nm', seg_name_(elt, seg), mode, ...
                      opts.poke_fig*1e9);
        ch = macos.channels.MonZernChannel(m, elt, mode);
        % dwdz columns are OPD-BaseUnits per coef-BaseUnits (the dwdz/
        % dwdg supervisors apply NO cbm scale, unlike dwdx) -- x cbm
        % converts the prediction to SI to match the engine delta
        do_poke_('z', lbl, elt, mode, ch, opts.poke_fig, ...
            col2map_(Bz(:, k)*opts.poke_fig*cbm, jnz), ...
            dmz.dldz(:, k)*opts.poke_fig, dmz.dedz(:, k)*opts.poke_fig, ...
            zeros(es.nmeas, 1));
    end
end

%% grid: per-segment influence pokes on the grid-augmented Rx of the
%% harvest, with the basis REBUILT by the same segment_grid_basis call
if any(chansel == "grid")
    og = J.og;
    grx = opts.grid_rx;
    if strlength(grx) == 0, grx = string(og.rx_path); end
    assert(isfile(grx), ['run_compare: grid-augmented Rx %s not found ' ...
        '(og.rx_path; pass ''grid_rx'')'], grx);
    if isfield(og, 'sgb') && ~isempty(og.sgb)
        % the harvest's own basis (run_sensitivities persists it) --
        % the only bit-exact source; a rebuild can rotate the last
        % G-S mode (session-dependent tie-break, 2026-07-19)
        sgb = og.sgb;
        say('\n[2g] grid: influence pokes (%g nm) on %s (harvest basis og.sgb):\n', ...
            opts.poke_fig*1e9, grx);
    else
        warning('run_compare:sgb_rebuild', ...
            ['og carries no sgb -- rebuilding the influence basis; ' ...
             'the last G-S mode may be rotated vs the harvest ' ...
             '(re-harvest with the current run_sensitivities to persist it)']);
        say('\n[2g] grid: influence pokes (%g nm) on %s (basis REBUILT -- see warning):\n', ...
            opts.poke_fig*1e9, grx);
        sgb = macos.segment_grid_basis(m, char(grx), ...
            'pm_ref_elt', opts.pm_ref_elt, 'modes', og.zmodes, ...
            'orthogonalize', true);
    end
    dmg = macos.design.dmet_dfig(seg, es, gmet, ...
        'g_names', og.channel_names, 'sgb', sgb, 'unit_to_m', cbm);
    say(['     linear l/e = dmdgrid (dmet_dfig at the mount points; ' ...
         'engine bars rigid-zero)\n']);
    % segment_grid_basis traces (and ray-hist pokes) the Rx to measure
    % footprints -- RELOAD before the baseline, exactly as the
    % dw_dgrid_multi harvest does, or the leftover state biases every
    % grid FD at the ~20% level (caught 2026-07-19)
    m.load_rx(char(grx));
    if ~isempty(opts.ngridpts), m.set_src_sampling(opts.ngridpts); end
    gch = macos.channels.grid_channels(m, sgb);
    names_g = cellfun(@(c) c.name(), gch, 'UniformOutput', false);
    icg = find(strcmp(og.field_names, 'C'), 1);
    assert(~isempty(icg), 'run_compare: dwdgrid jac has no center field');
    Bg = og.per_field_dwdg{icg};
    W0g = og.per_field_w_nom_2d{icg};
    wf_elt = m.num_elt() - 1;                 % new engine context
    m.trace(wf_elt);
    Wb = m.opd();  maskb = Wb ~= 0;
    l0b = [];                                 % no met blocks on the grid Rx
    assert(isequal(size(W0g), size(Wb)), ...
        'run_compare: dwdgrid canvas %dx%d vs engine %dx%d', ...
        size(W0g, 1), size(W0g, 2), size(Wb, 1), size(Wb, 2));
    [~, jng] = macos.m2v(W0g);
    for k = 1:numel(og.channel_names)
        i = find(strcmp(names_g, og.channel_names{k}), 1);
        assert(~isempty(i), ['run_compare: rebuilt grid basis lacks ' ...
            'channel %s -- pm_ref_elt/modes mismatch with the harvest'], ...
            og.channel_names{k});
        tok = regexp(og.channel_names{k}, '^Elt (\d+) Grid(\d+)$', ...
            'tokens', 'once');
        elt = str2double(tok{1});  gk = str2double(tok{2});
        lbl = sprintf('%s G%d %+g nm', seg_name_(elt, seg), gk, ...
                      opts.poke_fig*1e9);
        do_poke_('grid', lbl, elt, gk, gch{i}, opts.poke_fig, ...
            col2map_(Bg(:, k)*opts.poke_fig*cbm, jng), ...   % BU/BU -> SI
            dmg.dldg(:, k)*opts.poke_fig, dmg.dedg(:, k)*opts.poke_fig, ...
            zeros(es.nmeas, 1));
    end
end
if isfile(fullfile(fdir, 'tmp_e.png'))
    delete(fullfile(fdir, 'tmp_e.png'), fullfile(fdir, 'tmp_l.png'));
end

%% -- [3] agreement summary + dwdu export ------------------------------
say('\n[3] worst engine-vs-linear agreement per channel:\n');
worst = struct();
for c = ["x", "z", "grid"]
    tc = T(strcmp({T.chan}, c));
    if isempty(tc), continue; end
    [wv, iw] = max([tc.w_rel]);
    lv = max([tc.l_rel]);  ev = max([tc.e_rel]);   % NaN-ignoring
    say('    %-5s (%3d pokes): w %8s (%s), l %8s, e %8s\n', c, numel(tc), ...
        rel_txt_(wv), tc(max(iw,1)).label, rel_txt_(lv), rel_txt_(ev));
    worst.(char(c)) = struct('w', wv, 'l', lv, 'e', ev);
end
worst.w = max([T.w_rel]);  worst.l = max([T.l_rel]);  worst.e = max([T.e_rel]);
nnull = nnz(isnan([T.w_rel]));
if nnull > 0
    say('    (%d poke(s) below the %g nm response floor -- no physical\n', ...
        nnull, opts.w_floor*1e9);
    say('     response, engine delta is FD noise; rel = null)\n');
end
say(['    (rel = engine-vs-linear residual over the engine response;\n' ...
     '     at these poke sizes this measures the linearization error.\n' ...
     '     z/grid l/e: the LINEAR side shows the dmdz/dmdgrid figure-\n' ...
     '     sensing model (mode shape at each mount point); the ENGINE\n' ...
     '     METcalc/Hx hold met and sensor points RIGID, so its bars\n' ...
     '     read zero -- a known engine-model gap, not a failure.)\n']);
if ~isempty(dmz)
    say('    dmdz: |l| model up to %.4g nm, |e_piston| up to %.4g nm per %g nm figure\n', ...
        max(abs(dmz.dldz(:)))*opts.poke_fig*1e9, ...
        max(abs(dmz.dedz(:)))*opts.poke_fig*1e9, opts.poke_fig*1e9);
end
if ~isempty(dmg)
    say('    dmdgrid: |l| model up to %.4g nm, |e_piston| up to %.4g nm per %g nm figure\n', ...
        max(abs(dmg.dldg(:)))*opts.poke_fig*1e9, ...
        max(abs(dmg.dedg(:)))*opts.poke_fig*1e9, opts.poke_fig*1e9);
    say(['    NOTE (grid w rel): the truth is a plain forward poke at %g nm;\n' ...
         '    the harvest Jacobian is central-FD at %g (BaseUnits).  The\n' ...
         '    engine''s grid-surface response is NOT proportional across\n' ...
         '    sub-um amplitudes on metre-based prescriptions (central FD at\n' ...
         '    the harvest delta reproduces the Jacobian to ~2e-5; forward\n' ...
         '    100 nm deviates ~15-25%% on e2e, <5%% on the mm fixture) --\n' ...
         '    flagged for engine review (FreeForm grid intersection path,\n' ...
         '    2026-07-19).  x and z channels do not show this.\n'], ...
        opts.poke_fig*1e9, J.og.delta);
end
assert(~any(ismember(bodies(control), nochan)), ...
    'run_compare: a control body has no dwdx channels -- not actuatable');
ucols = reshape((control(:)-1)*6 + (1:6), 1, []);
dwdu = ox.dwdxall(:, colmap(sort(ucols)));
say('    control u = bodies [%s] -> dwdu %d x %d (multi-field stack) for the simulator\n', ...
    num2str(bodies(control)), size(dwdu, 1), size(dwdu, 2));

art = struct('table', T, 'frames_dir', fdir, 'gif', gif_file, ...
    'report', pth("_compare_report.txt"), 'mat', pth("_compare.mat"), ...
    'met_rx', char(met_rx), 'bodies', bodies, 'dofs', opts.dofs, ...
    'channels', chansel, 'poke_rot', opts.poke_rot, ...
    'poke_trans', opts.poke_trans, 'poke_fig', opts.poke_fig, ...
    'u_bodies', bodies(control), 'u_cols', sort(ucols), 'worst', worst);
art.dwdu = dwdu;
% figure-sensing measurement blocks (m = [l; e] order) for the
% simulator stage's estimator H -- Dave 2026-07-19
if ~isempty(dmz)
    art.dldz = dmz.dldz;  art.dedz = dmz.dedz;  art.dmdz = dmz.dmdz;
end
if ~isempty(dmg)
    art.dldg = dmg.dldg;  art.dedg = dmg.dedg;  art.dmdgrid = dmg.dmdgrid;
end
save(art.mat, '-struct', 'art', '-v7.3');
say('\nartifacts: %s_compare.mat, frames in %s_frames/%s, this report\n', ...
    name, name, iif_(opts.gif, sprintf(', %s_compare.gif', name), ''));
say('next stage: run_simulator (single-step static estimator + controller over a time history).\n');

% ---- nested: one poke = engine truth + linear + metrics + graphics ----
    function do_poke_(chan, lbl, body, dof, ch, poke, dW_l, dl_l, de_l, de_t)
        ip = ip + 1;
        ch.apply(poke);
        m.trace(wf_elt);
        Wp = m.opd();
        if ~isempty(l0b)
            dl_t = macos.met().l - l0b;
        else
            dl_t = zeros(size(dl_l));
        end
        ch.restore();
        dW_t = nan(size(Wb));
        mk = maskb & (Wp ~= 0);
        dW_t(mk) = (Wp(mk) - Wb(mk)) * cbm;
        cm = isfinite(dW_t) & isfinite(dW_l);
        wt = dW_t(cm);  wl = dW_l(cm);
        r = struct('chan', chan, 'label', lbl, 'body', body, 'dof', dof, ...
            'poke', poke, ...
            'w_rms_t', rms_(wt), ...
            'w_rel', rms_(wt - wl) / max(rms_(wt), eps), ...
            'l_max_t', max(abs(dl_t)), ...
            'l_rel', max(abs(dl_t - dl_l)) / max(max(abs(dl_t)), eps), ...
            'e_max_t', max(abs(de_t)), ...
            'e_rel', max(abs(de_t - de_l)) / max(max(abs(de_t)), eps), ...
            'l_max_m', max(abs(dl_l)), 'e_max_m', max(abs(de_l)));
        if r.w_rms_t < opts.w_floor, r.w_rel = NaN; end  % null response
        if r.l_max_t < opts.w_floor, r.l_rel = NaN; end  % z/grid + quiet
        if r.e_max_t == 0,           r.e_rel = NaN; end  % hub/aft, z/grid
        T(end+1) = r;
        if strcmp(chan, 'x')
            say('    %-22s w %8.3g nm rms (rel %8s) | l %8.3g nm (rel %8s) | e %8.3g nm (rel %8s)\n', ...
                lbl, r.w_rms_t*1e9, rel_txt_(r.w_rel), r.l_max_t*1e9, ...
                rel_txt_(r.l_rel), r.e_max_t*1e9, rel_txt_(r.e_rel));
        else                              % figure DOF: engine l/e rigid-zero
            say('    %-22s w %8.3g nm rms (rel %8s) | l mdl %8.3g nm | e_pist mdl %8.3g nm\n', ...
                lbl, r.w_rms_t*1e9, rel_txt_(r.w_rel), ...
                r.l_max_m*1e9, r.e_max_m*1e9);
        end

        % the two graphics (shared color/axis limits so they read as a pair)
        cmax = max([abs(dW_t(cm)); abs(dW_l(cm)); eps]) * 1e9;
        yl = { bar_lim_(dl_t, dl_l), ...
               bar_lim_(de_t(ie_p), de_l(ie_p)), ...
               bar_lim_(de_t(ie_g), de_l(ie_g)), ...
               bar_lim_(de_t(ie_s), de_l(ie_s)) };
        draw_side_(fe, sprintf('mmacos ENGINE | %s', lbl), dW_t, ...
            dl_t, de_t(ie_p), de_t(ie_g), de_t(ie_s), cmax, yl);
        draw_side_(fl, sprintf('LINEAR MODEL | %s', lbl), dW_l, ...
            dl_l, de_l(ie_p), de_l(ie_g), de_l(ie_s), cmax, yl);
        drawnow;
        if opts.visible && opts.dwell > 0, pause(opts.dwell); end

        % save the pair as one combined frame (+ GIF)
        f1 = fullfile(fdir, 'tmp_e.png');  f2 = fullfile(fdir, 'tmp_l.png');
        print(fe, f1, '-dpng', '-r100');  print(fl, f2, '-dpng', '-r100');
        A = imread(f1);  B = imread(f2);
        h = max(size(A, 1), size(B, 1));
        A(end+1:h, :, :) = 255;  B(end+1:h, :, :) = 255;
        C = [A, B];
        fr = fullfile(fdir, sprintf('p%03d_%s.png', ip, ...
            regexprep(lbl, '[^\w+-]', '_')));
        imwrite(C, fr);
        if opts.gif
            [q, cmp] = rgb2ind(C, 256);
            if ip == 1
                imwrite(q, cmp, gif_file, 'gif', 'LoopCount', Inf, ...
                    'DelayTime', max(opts.dwell, 0.05));
            else
                imwrite(q, cmp, gif_file, 'gif', 'WriteMode', 'append', ...
                    'DelayTime', max(opts.dwell, 0.05));
            end
        end
    end
end

% =========================================================================
function s = iif_(cond, a, b)
s = b;  if cond, s = a; end
end

function b = reset_eff_(v)
% Effective reset_xp bool from the tri-state stamp (true|false|'no-effect').
% 'no-effect' = FEX found no pupil to write == frozen-EP in practice.
if ischar(v) || isstring(v)
    b = ~strcmpi(string(v), 'no-effect');   % any other string -> true-ish
else
    b = logical(v);
end
end

function s = reset_str_(v)
% Human-readable reset_xp stamp for the mismatch message.
if ischar(v) || isstring(v), s = char(string(v));
else, s = mat2str(logical(v)); end
end

function v = rms_(x)
v = sqrt(mean(x(:).^2));
end

function s = rel_txt_(v)
if isnan(v), s = 'null';  else, s = sprintf('%.2e', v); end
end

function M = col2map_(col, jn)
%COL2MAP_  Scatter an m2v-ordered column back onto its 2D canvas.
M = nan(jn.size);
M(sub2ind(jn.size, jn.i, jn.j)) = col;
end

function yl = bar_lim_(a, b)
v = max([abs(a(:)); abs(b(:)); eps]) * 1e9 * 1.15;
yl = [-v, v];
end

function draw_side_(fig, ttl, W2, l, ep, eg, esh, cmax, yl)
%DRAW_SIDE_  One model's graphic: OPD map above l/e_piston/e_gap/e_shear bars.
clf(fig);
tl = tiledlayout(fig, 6, 1, 'Padding', 'compact', 'TileSpacing', 'compact');
title(tl, ttl, 'Interpreter', 'none', 'FontWeight', 'bold');
ax = nexttile(tl, [2 1]);
im = imagesc(ax, W2 * 1e9);                   % same canvas convention as
set(im, 'AlphaData', isfinite(W2));           % plot_dw_per_element (s4 pages)
axis(ax, 'image');  set(ax, 'XTick', [], 'YTick', []);
clim(ax, [-cmax, cmax]);  colormap(ax, parula);
cb = colorbar(ax);  cb.Label.String = '\DeltaOPD (nm)';
title(ax, 'center-field OPD change', 'FontWeight', 'normal');
panels = {l, 'l (nm)'; ep, 'e piston (nm)'; eg, 'e gap (nm)'; ...
          esh, 'e shear (nm)'};
for p = 1:4
    ax = nexttile(tl);
    bar(ax, panels{p, 1} * 1e9, 'FaceColor', [0.2 0.45 0.75]);
    ylim(ax, yl{p});  grid(ax, 'on');
    ylabel(ax, panels{p, 2});
    if p < 4, set(ax, 'XTickLabel', []); end
end
xlabel(ax, 'measurement index');
end

function nm = body_name_(k, nseg, bodies)
if k <= nseg
    nm = sprintf('Seg %d', k);
elseif k == nseg + 1
    nm = sprintf('hub e%d', bodies(k));
else
    nm = sprintf('aft e%d', bodies(k));
end
end

function nm = seg_name_(elt, seg)
s = find(seg.seg_elts == elt, 1);
if ~isempty(s), nm = sprintf('Seg %d', s);
else,           nm = sprintf('elt %d', elt);
end
end

function de = e_truth_(es, seg, cbm, s, th, dl)
%E_TRUTH_  Finite-rotation edge-sensor readings for a poke of segment S.
%   The sensor axis (recovered from the row's translation block -- the
%   measurement model itself) and the arm from the segment reference
%   point to the Hx SensorPos are exact; the rotation uses the full
%   Rodrigues matrix, so truth-vs-dedx differences are the genuine
%   linearization error.  th/dl in the segment triad, SI; de in SI.
de = zeros(es.nmeas, 1);
f = seg.frames(s);
Ts = [f.xhat, f.yhat, f.zhat];
thw = Ts * th;
R = rodrigues_(thw);
dlw = Ts * dl / cbm;                          % world, BaseUnits
for q = find(any(es.meas_to_seg == s, 1))
    blk = es.dedx(q, (s-1)*6 + (4:6)).';      % signed axis, triad comps
    a = Ts * blk;
    rho = es.sensor_pos(:, q) - f.rpt;
    de(q) = (a.' * ((R - eye(3))*rho + dlw)) * cbm;
end
end

function R = rodrigues_(w)
t = norm(w);
if t < 1e-300, R = eye(3); return; end
k = w / t;
K = [0 -k(3) k(2); k(3) 0 -k(1); -k(2) k(1) 0];
R = eye(3) + sin(t)*K + (1 - cos(t))*(K*K);
end

function [B, colmap, nochan] = dwdx_cols_(Bf, cn, bodies)
%DWDX_COLS_  Sensed bodies' 6-DOF columns in [rot|trans] order.  A body
%   with no channels in the harvest (Reference / FocalPlane-class --
%   e.g. an aft met ring riding the FPA) gets ZERO columns: the plain
%   engine trace has no wavefront response to it either, so zero IS
%   the matching linear model; its element id is returned in NOCHAN.
DOFN = {'Rx', 'Ry', 'Rz', 'Tx', 'Ty', 'Tz'};
nb = numel(bodies);
B = zeros(size(Bf, 1), 6*nb);
colmap = zeros(1, 6*nb);
nochan = [];
for b = 1:nb
    for d = 1:6
        i = find(strcmp(cn, sprintf('Elt %d %s', bodies(b), DOFN{d})), 1);
        if isempty(i)
            nochan(end+1) = bodies(b); %#ok<AGROW>
            break
        end
        B(:, (b-1)*6 + d) = Bf(:, i);
        colmap((b-1)*6 + d) = i;
    end
end
nochan = unique(nochan);
end

function M = met_struct_(met)
%MET_STRUCT_  Accept a run_met .mat path or an equivalent struct.
if isstruct(met), M = met;
else
    assert(isfile(met), 'run_compare: met .mat %s not found', met);
    M = load(met);
end
for f = {'dedx', 'dldx', 'bodies', 'seg', 'met_in'}
    assert(isfield(M, f{1}), 'run_compare: met struct lacks %s', f{1});
end
end

function J = jac_all_(jac)
%JAC_ALL_  Accept the s4 .mat (ox + optional oz/og fields), a raw .mat
%   of dw_d*_multi outputs, or the ox struct itself.  ox is required
%   and must carry per-field blocks; oz/og enable the z/grid phases.
J = struct('ox', [], 'oz', [], 'og', []);
if isstruct(jac) && isfield(jac, 'ox')
    J.ox = jac.ox;
    if isfield(jac, 'oz'), J.oz = jac.oz; end
    if isfield(jac, 'og'), J.og = jac.og; end
elseif isstruct(jac) && isfield(jac, 'dwdxall')
    J.ox = jac;
else
    assert(isfile(jac), 'run_compare: jac .mat %s not found', jac);
    S = load(jac);
    if isfield(S, 'ox'), J.ox = S.ox; end
    if isfield(S, 'oz'), J.oz = S.oz; end
    if isfield(S, 'og'), J.og = S.og; end
    if isempty(J.ox)
        fn = fieldnames(S);
        for k = 1:numel(fn)
            v = S.(fn{k});
            if isstruct(v) && isfield(v, 'dwdxall') ...
                    && isfield(v, 'channel_names') ...
                    && any(~cellfun('isempty', regexp(v.channel_names, ...
                        '^Elt \d+ [RT][xyz]$', 'once')))
                J.ox = v;  break
            end
        end
    end
    assert(~isempty(J.ox), ...
        'run_compare: no dw_dx_multi rigid-body output in %s', jac);
end
for f = {'per_field_dwdx', 'per_field_w_nom_2d', 'field_names', 'dwdxall'}
    assert(isfield(J.ox, f{1}), ...
        'run_compare: jac lacks %s (re-harvest with the multi supervisor)', f{1});
end
if ~isempty(J.oz)
    assert(isfield(J.oz, 'per_field_dwdz'), ...
        'run_compare: oz lacks per_field_dwdz');
end
if ~isempty(J.og)
    assert(isfield(J.og, 'per_field_dwdg') && isfield(J.og, 'rx_path') ...
        && isfield(J.og, 'zmodes'), ...
        'run_compare: og lacks per_field_dwdg/rx_path/zmodes');
end
end
