% cf1b_probe -- the stopped aperture-matched prolate hit the 5000-iter cap
% unconverged (cf1 conv=0) and scored 4x worse than no-stop.  Does a 20000
% cap converge it, and does the dark zone move?
here = fileparts(mfilename('fullpath'));
run(fullfile(here,'..','..','..','mmacos_setup.m'));
P = e2e6m_r2_params(struct());
addpath(fullfile(here,'..','..','30_instruments','bench_ctb'));
ch = cf_chain('rx', fullfile(P.outdir,'r1_seg_prop.in'), ...
              'model_size', P.co.model, 'prolate_iter', 20000, ...
              'circ_stop_frac', P.cf.circ_stop_frac, ...
              'apod_kind','prolate_seg', 'fpm_kind','hard', ...
              'r_fpm_lamD', P.co.r_occ_lamD, 'r_lyot_frac', P.co.r_lyot_frac);
pi_ = ch.prolate_info;
fprintf('PROBE prolate: lambda0=%.6f conv=%d iters=%d\n', ...
        pi_.lambda0, pi_.converged, pi_.n_iter_used);
E = ch.run();  I = abs(E).^2;
dz = macos.dark_zone_metrics(I, ch.peak_bare, ch.lamD_px, ...
                             P.co.inner_lamD, P.co.outer_lamD);
fprintf('PROBE dz: mean %.4e median %.4e (cf1@5000: 2.179e-06 / 2.258e-07)\n', ...
        dz.mean, dz.median);
