#!/usr/bin/env python3
"""Build the rodgers3 RE-WALK deck (deck_rodgers3_walk.pptx) -- deck 2.

Deck 1 (deck_rodgers3.py) argues the result; this deck teaches the
solution: a CodeV-literate reader re-walks the whole arc from this deck
plus the repo.  Genre: WORKBOOK (DECK2_PLAN.md) -- ~16 content slides in
six lettered sections; the STYLE_REPORTS SS3 budget deviation is
declared on the cover and in the plan, for Dave's waive/trim.

Same discipline as deck 1: every number parsed from committed records
(rodgers3_records.py), figures = committed PNGs, built via the
committed make_brief_slides.py.  Never hand-edit the .pptx.

Slide 15 (the unguided re-instance experiment) self-updates: if
t5_unguided_REPORT.md exists beside this script its VERDICT line is
quoted; until then the slide states the protocol and marks the result
pending (BRIEF_oi_unguided is the instrument).

Run:  python3 deck_rodgers3_walk.py
"""
import os
import re
import subprocess
import sys

from rodgers3_records import load, need, read

HERE = os.path.dirname(os.path.abspath(__file__))
T4REL = "../../templates/10_telescopes/offset_imager/t4_wide"

gates, t3, pk = load()
his = {g["rung"]: g["his"] for g in gates}

DEG, MU, LAM = "°", "µ", "λ"
PM, LE, GE = "±", "≤", "≥"

TAG = ("strict RMS WFE, centroid reference on the stage's frozen focal "
       "plane, exit-pupil anchor, piston-only removal; quoted statistic = "
       "dense 11x11 map MAXIMUM over the field box")

GATEROWS = "".join(
    f"| {g['rung']} | {g['his']:.0f} | {g['ours']:.2f} | {g['ratio']:.3f} | "
    f"{g['verdict']} |\n" for g in gates).rstrip("\n")

# slide 15: quote the unguided-experiment verdict if the report exists
t5_path = os.path.join(HERE, "t5_unguided_REPORT.md")
if os.path.exists(t5_path):
    t5txt = read(t5_path)
    m = re.search(r"VERDICT[^\n]*", t5txt)
    T5LINE = ("Result: " + m.group(0)) if m else \
        "Result: t5_unguided_REPORT.md present but carries no VERDICT line."
else:
    T5LINE = ("Result: PENDING -- the run is in progress; this slide "
              "updates itself from t5_unguided_REPORT.md at the next build.")

MD = f"""<!-- rodgers3 RE-WALK deck (deck 2).  GENERATED by
     deck_rodgers3_walk.py -- edit the generator, not this file. -->

# Re-Walking the Offset-Field Imager
A workbook: from the committed truth files to the gated ladder
D. C. Redding with Claude Code — 22 August 2026.  Companion to the story deck (deck_rodgers3); source study M. Rodgers, 260802-WFOVimager_Offsetfield.  Everything quoted here is parsed from the committed records of MACOS_resources mmacos/challenges/rodgers3 + templates/10_telescopes/offset_imager.
~ THE METRIC CONTRACT, once for the whole deck: {TAG}.  Every WFE number on every slide inherits it.  Workbook genre: 16 content slides in six sections (budget deviation declared, DECK2_PLAN.md).  DRAFT — pending sign-off.

## A1 — The problem, and everything needed is committed | Three mirrors, a 20{DEG}x20{DEG} box at 22{DEG}, an exit pin, hard clearances — and five reported rungs to meet
::: left
- The system: EPD 75 mm, F/4 (EFL 300 mm), {LAM} = 1 {MU}m, field box 20{DEG}x20{DEG} full width at YAN +22{DEG}; exit beam horizontal (rung 2 on); clearances > 50 / > 35 mm (rung 4 on); 9-point optimization field, XAN {PM}10{DEG}.
- The reproduction inputs are IN the repo: five CODE V lens sequences (the truth), the machine-generated reader (rodgers3_seq), the template, the tests, and the packet.  The source presentation is referenced, not committed — nothing below depends on it.

| rung | design state | reported nm |
| r1 | coaxial, on-axis box, aspheres | {his['r1']:.0f} |
| r2 | same mirrors, offset box, FPA refit | {his['r2']:.0f} |
| r3 | re-asphered at the offset | {his['r3']:.0f} |
| r4 | + tilt/decenter + radii | {his['r4']:.0f} |
| r5 | + 8th-order Zernike + radii | {his['r5']:.0f} |
::: right
![The instrument class, traced: the coaxial stage of the reproduction.](t3/r3t_s1_layout.png){{h=4.4}}
~ Repo map: challenges/rodgers3/ (decks *.seq -> rodgers3_seq.m, rodgers3.m, run_t3.m, run_s5_budget.m, run_s5_signed.m, PACKET.md) + templates/10_telescopes/offset_imager/ (the template) + design/src (oi_score, oi_clear) + tests (tRodgers3, tOffsetImager).

## A2 — Read the truth, decode the conventions, gate the decode | Five conventions had to be established — each carries its own falsifier
::: left
| convention | decode | its gate |
| focal ratio | thicknesses, NOT stations: th4 −722.9 / th6 +740.8 mm -> F/4.00004 | stations misread gives F/4.95 — retracted in place; runner reads the .seq at runtime |
| the reported statistic | MAX of the dense RMS-vs-field map (from the slides' own embedded plot metadata) | five rungs reproduce in [0.8, 1.25]x |
| Zernike basis | BornWolf, mode = C-index MINUS ONE | dropping the offset misses rung 5 by {pk['zrn_negctl']:.0f}x |
| tilt/decenter | decenters verbatim, tilt sense flipped | origin discriminant + map-shape check |
| stop aiming | native ChiefRayAiming at the stop Reference | A/B vs Newton aiming: {LE} 0.04 nm |
::: right
| rung | reported nm | reproduced | ratio | verdict |
{GATEROWS}
- The reproduction is the licence for every comparison after it: same metric, same statistic, same sampling, both sides.  Nothing was tuned toward the reported values — the band IS the measurement.
::: full
~ Claim of this slide: decode conventions, then GATE the decode with a falsifier that has teeth.  A convention without its negative control is a guess (r3_s0_report.txt carries the full caveat list).

## B3 — The template | Five stages; first-order identities are re-derived every iterate, never penalized
::: left
::: stack
- S1 · coaxial solve :: first-order seed (EFL = EPD x F#, Petzval = 0), then conics + aspheres at the on-axis box
- S2 · the move :: the same mirrors at the offset box; only the focal plane follows
- S3 · re-solve at the used field :: symmetric surfaces re-solved at the offset, from the better of two starts
- S4 · tilt/decenter under constraints :: exit direction + clearances enter the solve as residual rows
- S5 · Zernike departures :: aspheres replaced; power pinned to the radii, tilt to the pointing
::: right
- Identities enforced by construction: EFL exact at every iterate; Petzval zero in the symmetric stages; the stop pose re-derived (and BOUNDED — a degenerate pupil construction falls back to the pose that traced); the focal plane re-posed per stage.
- Pinning doctrine: power belongs to the radii, tilt to the pointing — freeing them into the figure basis makes the solve fight its own pins (slide D12, counter b).
- One call runs the whole story: oi_story(params) = ladder + counters + report.  The challenge instance is run_t3.m — a thin wrapper that reads the .seq truth at runtime.
~ Template: templates/10_telescopes/offset_imager.  Every stage emits its deck (.in), figures, and a REPORT section — the records this deck is parsed from.

## B4 — The solver | Per-ray residuals with vertex-radial scales; the solve set must be sized to the variables
::: left
- Residuals are PER-RAY wavefront errors stacked over the solve fields — per-field RMS residuals stall: the scalar hides the gradient direction, and the table's S1 row is what per-ray recovers.
- Natural scales are VERTEX-RADIAL: aspheres and Zernike-lMon terms are r^n about the vertex, so an offset beam's lever arm is |footprint centre| + its radius.  Footprint-centred radii under-scale r^8 by orders of magnitude and finite-difference steps then destroy the surface.
- Damped Gauss–Newton with a chord (one Jacobian reused up to 3 accepted steps), trust-radius damping, and a plateau stop (< 0.1%/iteration after warm-up).
- SIZE THE SOLVE SET TO THE VARIABLES: 9 fields against 82 Zernike variables under-determines the solve — the solve set converges while the dense map stalls (measured on slide C11; 25 fields resolve it).  The dense map is always the score; the solve set is only what the optimizer sees.
::: right
| stage | vars | fields | start -> qmean (nm) | iters |
| S1 | 15 | 9 | {t3['s1']['rms0']:.0f} -> {t3['s1']['rms']:.1f} | {t3['s1']['iters']} |
| S3 | 16 | 9 | {t3['s3']['rms0']:.0f} -> {t3['s3']['rms']:.1f} | {t3['s3']['iters']} |
| S4 | 23 | 9 | {t3['s4']['rms0']:.0f} -> {t3['s4']['rms']:.1f} | {t3['s4']['iters']} |
| S5 | 83 | 9 | {t3['s5']['rms0']:.0f} -> {t3['s5']['rms']:.1f} | {t3['s5']['iters']} |
- Reading the table: S5's 83 variables against 9 fields is the under-determined row — its dense-map stall and the fix are slide C11.
~ Solver: oi_solve (template dir).  The qmean column is over the SOLVE set; headline numbers are always the dense map.

## B5 — Constraints are rows, and drawings are gates | A wall freezes; a hinge pays; a pierced hinge must go NEGATIVE
::: left
- The exit-beam pin is an EQUALITY row (weighted residual), not a wall: a boolean wall freezes any stage that STARTS outside tolerance — the base Jacobian becomes all wall rows and no step can be evaluated.
- Clearances: nine ordered beam-leg/obstacle pairs, per-field glass patches (footprint disks x1.15, or 1.15-scaled convex hulls), the FP counted as an obstacle, evaluated over the field box — the centre field alone misses edge-field blockage.  The SAME model is the solve's hinge rows and the report's gate.
- The measure must test PIERCING exactly and return MINUS the penetration depth inside the glass.  Both halves were learned the hard way: a 25-sample walk reported millimetres of clearance for beams THROUGH a mirror, and a zero-at-contact measure gives the optimizer no slope to climb out — the solve re-converges on the blocked design.
- The defect was caught by READING THE LAYOUT FIGURE against the gate, not by any number.  Hardware drawings are gates, not illustrations.
::: right
![The exhibit: a second instance's beams thread M1 and M2 while the sampled gate reported PASS.  The instance is retired; the measure is fixed and gated.](t4_exhibit){{h=4.3}}
~ Measure: design/src/oi_clear (signed, piercing-exact, ray-paired; reference floors gated).  Full defect record: PACKET.md, 2026-08-21 addendum SSA.

## B6 — Scoring and gates | Solve set != scoring set; gates carry a knee; two glass models
::: left
- Every reported number is the dense 11x11 map MAXIMUM under the cover's metric contract — the statistic the source study's own slides quote (decoded and gated on A2).
- oi_gates: exit pin PASS at {LE} tolerance; clearance PASS at {GE} min(spec) − 1.5 mm (the hinge knee); WARN below the larger spec value.
- Two glass models, one knob (P.clear_footprint): 'disk' (footprint centre + 1.15x radius — the model of record) and 'hull' (1.15-scaled convex hull — tighter on elongated off-axis patches).  The S4 design of record reads {t3['s4']['clear_mm']:.1f} mm under disk (confirmed at fine sampling) and {pk['s4_hull']:.1f} mm under hull.
- The solve must pay what the gate measures: hinge rows and report gates share the model and the knob.
::: right
![S4 field envelopes: the gate's geometry — every leg vs every mirror edge, over the field box.](t3/r3t_s4_fields.png){{h=3.9}}
~ {TAG}.

## C7 — S1, the on-axis anchor | {t3['s1']['max_nm']:.1f} nm over the on-axis box (reported rung 1: {his['r1']:.0f})
::: left
- What is varied: conics + aspheres (radii through the EFL/Petzval closure).  What is held: packaging (from the .seq truth), the on-axis box.
- The solve runs {his['r1']/t3['s1']['max_nm']:.0f}x deeper than the source rung — depth that S2 will tax (next slide).
- Walk: oi_story(...) stage 1, or run_t3() for the challenge instance verbatim.
::: right
![S1 map: {t3['s1']['max_nm']:.1f} nm max; avg {t3['s1']['avg_nm']:.1f}.](t3/r3t_s1_map.png){{h=3.7}}
~ {TAG}.  S1–S3 are unconstrained; clearance floors are reported for context only.

## C8 — S2, the disaster is the pedagogy | {t3['s2']['max_nm']:,.0f} nm when the box moves 22{DEG} with the design frozen
::: left
- Only the focal plane may follow (tilt/focus refit).  The cost: {t3['s1']['max_nm']:.1f} -> {t3['s2']['max_nm']:,.0f} nm — {t3['s2']['max_nm']/his['r2']:.0f}x the reported {his['r2']:.0f}, because the deeper on-axis optimum pays proportionally more off axis.
- The rung measures the S1 DESIGN as much as the offset: harder-tuned aspheres fall harder.  Expect your own S2 to scale with your S1 depth, not with the reported value.
::: right
![S2 map: the price of moving the box with the design frozen.](t3/r3t_s2_map.png){{h=3.7}}
~ {TAG}.

## C9 — S3, re-solve at the used field | {t3['s3']['max_nm']:.1f} nm (reported: {his['r3']:.0f}) — from the better of TWO starts
::: left
- The two-candidate start is load-bearing: at a large offset the on-axis-optimized aspheres are poison ({t3['s3']['rms0']/1e3:.1f} {MU}m for the fresh Petzval-flat spheres vs far worse for the carry), but at a MILD offset the carry wins — score both at the used field, start from the winner.
- Conic migration under the bias doctrine (solve at the used field): K1 {t3['s1']['K'][0]:.2f} -> {t3['s3']['K'][0]:.2f} (oblate class).  Expect sign flips; they are the doctrine working, not an error.
- The stop pose is constructed ONCE at stage entry and frozen; from here the stop decenter is a solve variable driven by the exit row.
::: right
![S3 map: re-solved at the offset box.](t3/r3t_s3_map.png){{h=3.7}}
~ {TAG}.

## C10 — S4, buildability | {t3['s4']['max_nm']:.1f} nm at a {t3['s4']['clear_mm']:.1f} mm floor (confirmed) vs the reported {his['r4']:.0f} at {GE} 35 — {t3['s4']['max_nm']/his['r4']:.2f}x
::: left
- Unconstrained, tilt/decenter reach {pk['s4_unc']:.1f} nm — with the M3-to-FP beam through M2's patch.  Not buildable; the map alone cannot tell you.
- With the clearance rows paying the nine-pair model: {t3['s4']['max_nm']:.1f} nm at {t3['s4']['clear_mm']:.1f} mm ({pk['s4_hull']:.1f} mm under the hull model).  Two toolchains, same constraint, same answer to 3% — and the constraint's measured price is {t3['s4']['max_nm']/pk['s4_unc']:.1f}x in WFE.
- Exit chief within 0.03{DEG} of horizontal at every stage (the equality row, not a wall).
::: right
![S4 map: {t3['s4']['max_nm']:.1f} nm max over the box.](t3/r3t_s4_map.png){{h=3.7}}
~ {TAG}.  The floor is fine-sampling-CONFIRMED under the fixed measure (addendum SSA).

## C11 — S5, diagnosed then beaten | The gap to the reported {his['r5']:.0f} was the solve-field count; matching it lands {pk['legC_nm']:.1f} nm
::: left
- The five-stage run closes at {t3['s5']['max_nm']:.1f} nm — stalled at its S4 level, 83 variables against 9 solve fields.
- The controlled probes, all from the identical S4 seed (the printed start reproduces the record's 2150.1 nm — your re-walk should too):

| probe | fields | iters | map max | true floor |
| S5 of record | 9 | 30 (cap) | {t3['s5']['max_nm']:.1f} | {pk['s5_true_floor']:.1f} mm |
| A | 9 | 150 | {pk['legA_nm']:.1f} | {pk['legA_mm']:.1f} mm |
| B | 25 | 60 | {pk['legB_nm']:.1f} | {pk['legB_mm']:.1f} mm |
| C (honest rows) | 25 | 49 (plateau) | {pk['legC_nm']:.1f} | {pk['legC_mm']:.1f} mm |
- Iterations are not the gap (A); fields are (B); with the fixed clearance rows the template lands {pk['legC_nm']:.1f} nm — {pk['legC_nm']/his['r5']:.2f}x the reported {his['r5']:.0f} — at a floor 1.6 mm shy of the stated 35 (the rows bought back what the blind measure had conceded).
::: right
![The honest re-solve (probe C): {pk['legC_nm']:.1f} nm max, true floor {pk['legC_mm']:.1f} mm.](s5_budget/s5b_legC_map.png){{h=3.7}}
~ {TAG}.  The of-record S5 clearance ({t3['s5']['clear_mm']:.1f} mm recorded) retracts to {pk['s5_true_floor']:.1f} mm under the fixed measure — addendum SSB carries the whole table.

## D12 — Counter-designs bound the space | Same constraints, same budget: the sphere+Zernike start wins; releasing the pins chokes
::: left
- (a) Sphere + Zernike from the start (no asphere heritage): {pk['ca']:.1f} nm vs the heritage path's {t3['s5']['max_nm']:.1f} — the heritage is a burden, not a head start.  The unconstrained variant ({pk['ca_unc']:.1f} nm) did NOT survive buildability: always re-check a counter under the full constraint set.
- (b) Power + y-tilt released into the Zernike basis: {pk['cb']:.1f} nm — the freed modes fight the jobs the pins already do.  No evidence the reported {his['r5']:.0f} is term-set-limited; affirmative evidence for the pinning doctrine.
::: right
![Counter (a): {pk['ca']:.1f} nm under the full constraint set.](t3/r3t_ca_map.png){{h=2.5}}
![Counter (b): {pk['cb']:.0f} nm — the solve chokes.](t3/r3t_cb_map.png){{h=2.5}}
~ {TAG}.

## D13 — The gate map | Every claim in this deck lives in a committed test
::: full
| claim | where it is gated | the gate |
| the five-rung reproduction | tests/tRodgers3.m | per-rung bands around [0.8, 1.25]x (coarsened 5x5 maps) |
| the Zernike-basis decode | tRodgers3 negative control | C-offset dropped must miss by > 100x (measured {pk['zrn_negctl']:.0f}x) |
| the clearance measure | oi_clear reference floors | S4 {pk['s4_true_floor']:.2f} / S5 {pk['s5_true_floor']:.2f} mm reproduce exactly post-change |
| the template flow | tests/tOffsetImager.m | structural smoke: S1-S3 run and recover at reduced knobs |
| the promotion/graphics layer | freeform suite group | 128 pass / 0 fail on the merged tree (2026-08-21) |
- The suite is the arbiter of "reproduced": if your re-walk passes the freeform group, you have the solution.  If a number drifts outside a band, the gate names the rung and the convention to re-check.
~ Run: ./run_mmacos_tests.sh freeform (mmacos root).

## E14 — The re-walk, verbatim | Four commands, their runtimes, and what "reproduced" means
::: left
```
run mmacos_setup.m
rodgers3();        % Stage-0 gate ladder      (~40 min)
run_t3();          % template at the challenge
                   %   + counters             (~4 h)
run_s5_budget();   % probes A + B             (~8 h)
run_s5_signed();   % probe C, honest rows     (~4 h)
./run_mmacos_tests.sh freeform   % the arbiter (~1 h)
```
::: right
- Artifacts land beside the runners: challenges/rodgers3/t3/ (decks, figures, REPORT), s5_budget/ (probe maps + .mat), and the packet quotes all of it.
- "Reproduced" means: the five rungs inside their tRodgers3 bands; the probe-C start printing ~2150.1 nm (the seed self-check); the clearance reference floors to 0.01 mm; the suite green.  Map maxima are digit-stable on one engine build; across compilers expect round-off-level drift only.
- Every figure in this deck regenerates from the committed .mats without re-solving (the deck generators parse the records — nothing is hand-typed).
~ {TAG}.

## F15 — Can a new user re-instance it without an agent? | The experiment is running; its protocol is the point
::: left
- The claim under test: "a re-do at different parameters is ONE CALL."  The instrument: an agent restricted to the COMMITTED docs only (README, packet + addendum, function help) — no lore files, no memory, no fixes allowed — plays the new-user proxy at a fresh instance: EPD 150 mm, F/3.3, 15{DEG}x15{DEG} at 22.5{DEG}, clearances > 40 / > 25 mm, exit horizontal.
- The PACKAGING ENVELOPE is deliberately left to the docs: whether a documented feasibility screen (the field-walk rule, addendum SSC) gets found and applied is part of the measurement.
- The deliverable either way: a verdict plus a verbatim FRICTION LIST — every silence, wrong turn, and guess.  A negative result is a valid result.
- {T5LINE}
::: right
- Why it matters here: the retired second instance (slide B5's exhibit) failed precisely where documentation had not yet compiled the lesson.  This experiment measures how far the NOW-committed docs and gates carry an unassisted user.
~ Protocol: BRIEF_oi_unguided (repo-external instrument; the report commits as challenges/rodgers3/t5_unguided_REPORT.md).

## F16 — Should mmacos embed an agent helper? | Questions for this audience
::: left
- The evidence FOR, from this arc: every defect found was a CONCEPTUAL coupling — a frame convention, a metric reference, a constraint model — that documentation had not prevented; agent-in-the-loop found and fixed each in hours; the gotcha corpus already exists and could ship as a runtime advisor (macos.assist: "you are poking a segment whose grid frame differs from its Mon frame — the response will not localize").
- The evidence AGAINST, from the same arc: every fix COMPILED into a check — the prescription validator, the pose bound, the signed piercing measure, the gate map of D13.  Compiled knowledge is inspectable, testable, and maintenance-stable; a runtime assistant is none of those by default.  Slide F15 measures how far docs + gates alone go.
::: right
- Where is the line between knowledge compiled into checks and knowledge served by an assistant?
- What should a helper catch AT CALL TIME that a validator cannot?
- Who maintains the helper's knowledge when the engine moves — and how is IT gated?
- Would you trust a design whose constraint model was chosen by the assistant?
~ Discussion slide: questions are the deliverable.  Positions welcome; the F15 result will move this debate one way or the other.
"""

MD = MD.replace("(t4_exhibit)", f"({T4REL}/t4_s5_fields.png)")

md_path = os.path.join(HERE, "deck_rodgers3_walk.md")
with open(md_path, "w", encoding="utf-8") as f:
    f.write(MD)
print("wrote", md_path)

rc = subprocess.call([sys.executable,
                      os.path.join(HERE, "make_brief_slides.py"),
                      md_path, os.path.join(HERE, "deck_rodgers3_walk.pptx")])
sys.exit(rc)
