#!/usr/bin/env python3
"""Parse the five rodgers3 CODE V .seq decks into a MATLAB truth struct.

Emits rodgers3_seq.m -- the analogue of rodgers1's hand-transcribed
rodgers_seq.m, but machine-generated so every 16-digit value is verbatim.
Continuation lines end with '&'. Statements split on ';'.
"""
import re, sys, os

SRC = os.path.dirname(os.path.abspath(__file__))
FILES = {
    'r1': 'TML_Coaxial_OnAxisFOV.seq',
    'r2': 'TML_Coaxial_22degOffsetFOV.seq',
    'r3': 'TML_Coaxial_22degOffsetFOV_NewASP.seq',
    'r4': 'TML_TilDec_22degOffsetFOV_NewASPradii.seq',
    'r5': 'TML_TilDec_22degOffsetFOV_NewZRNradii.seq',
}

def logical_lines(path):
    raw = open(path).read().replace('\r\n','\n').replace('\r','\n')
    # join continuations: a line ending in '&' continues
    joined, buf = [], ''
    for ln in raw.split('\n'):
        s = ln.rstrip()
        if s.endswith('&'):
            buf += s[:-1] + ' '
        else:
            joined.append(buf + s); buf = ''
    if buf: joined.append(buf)
    # split on ';' into statements, keep order
    out = []
    for ln in joined:
        for st in ln.split(';'):
            st = st.strip()
            if st: out.append(st)
    return out

def parse(path):
    d = {'surfs': [], 'hdr': {}}
    cur = None
    for st in logical_lines(path):
        tok = st.split()
        key = tok[0]
        if key in ('RDM','TITLE','INI','CA','GO','LEN') or st.startswith('RDM'):
            if key == 'TITLE':
                d['hdr']['title'] = st.split("'")[1]
            continue
        if key in ('EPD','WL','REF','WTW'):
            d['hdr'][key] = float(tok[1]); continue
        if key == 'DIM':
            d['hdr']['DIM'] = tok[1]; continue
        if key in ('XAN','YAN'):
            d['hdr'][key] = [float(x) for x in tok[1:]]; continue
        if key in ('SO','S','SI'):
            cur = {'type': key, 'R': float(tok[1]), 'th': float(tok[2]) if len(tok)>2 else 0.0,
                   'refl': 'REFL' in tok, 'sco': {}, 'flags': []}
            d['surfs'].append(cur); continue
        if cur is None: continue
        if key == 'SLB':
            cur['label'] = st.split('"')[1]
        elif key in ('STO','DAR','ASP'):
            cur['flags'].append(key)
        elif key == 'SPS':
            cur['sps'] = tok[1]; cur['nradius_arg'] = float(tok[2])
        elif key == 'K':
            cur['K'] = float(tok[1])
        elif key in ('A','B','C','D'):
            cur.setdefault('asph', {})[key] = float(tok[1])
        elif key in ('XDE','YDE','ZDE','ADE','BDE','CDE'):
            cur[key] = float(tok[1])
        elif key == 'SCO':
            cur['sco'][tok[1]] = float(tok[2])
        elif key in ('CUF','CUM','THM','SCC'):
            pass  # cosmetic / freeze flags
        else:
            print(f'  [unhandled: {st[:50]}]', file=sys.stderr)
    return d

def mfloat(x):
    return repr(x)

with open('rodgers3_seq.m','w') as f:
    f.write("function S = rodgers3_seq()\n")
    f.write("%RODGERS3_SEQ  CODE V .seq TRUTH for the Rodgers3 offset-field imager.\n")
    f.write("%   MACHINE-GENERATED by parse_seq.py from the five decks Mike supplied\n")
    f.write("%   2026-08-19 (Creation Date 2-Aug-2026 in the decks).  Do not edit by\n")
    f.write("%   hand -- rerun the parser.  Values verbatim; CODE V sign conventions\n")
    f.write("%   (see rodgers1/rodgers_seq.m for the syntax decode; parity rule in\n")
    f.write("%   rodgers1/convention_decode.m).\n")
    f.write("    S = struct();\n")
    for tag, fn in FILES.items():
        d = parse(os.path.join(SRC, fn))
        f.write(f"\n    % ======== {fn} ========\n")
        f.write(f"    S.{tag}.file  = '{fn}';\n")
        f.write(f"    S.{tag}.title = '{d['hdr'].get('title','')}';\n")
        f.write(f"    S.{tag}.EPD_mm = {mfloat(d['hdr']['EPD'])};\n")
        f.write(f"    S.{tag}.WL_nm  = {mfloat(d['hdr']['WL'])};\n")
        f.write(f"    S.{tag}.XAN = [{' '.join(mfloat(x) for x in d['hdr']['XAN'])}];\n")
        f.write(f"    S.{tag}.YAN = [{' '.join(mfloat(x) for x in d['hdr']['YAN'])}];\n")
        for i, s in enumerate(d['surfs']):
            p = f"S.{tag}.s({i+1})"
            lbl = s.get('label','')
            f.write(f"    {p}.type = '{s['type']}'; {p}.label = '{lbl}';\n")
            f.write(f"    {p}.R = {mfloat(s['R'])}; {p}.th = {mfloat(s['th'])}; "
                    f"{p}.refl = {str(s['refl']).lower()};\n")
            f.write(f"    {p}.sto = {str('STO' in s['flags']).lower()}; "
                    f"{p}.dar = {str('DAR' in s['flags']).lower()};\n")
            if 'K' in s:
                f.write(f"    {p}.K = {mfloat(s['K'])};\n")
            if 'asph' in s:
                a = s['asph']
                f.write(f"    {p}.asph_ABCD = [{mfloat(a.get('A',0.0))} {mfloat(a.get('B',0.0))} "
                        f"{mfloat(a.get('C',0.0))} {mfloat(a.get('D',0.0))}];\n")
            for k in ('XDE','YDE','ZDE','ADE','BDE','CDE'):
                if k in s and s[k] != 0.0:
                    f.write(f"    {p}.{k} = {mfloat(s[k])};\n")
            if 'sps' in s:
                f.write(f"    {p}.sps = '{s['sps']}'; {p}.nradius = {mfloat(s['nradius_arg'])};\n")
            if s['sco']:
                sco = s['sco']
                if 'K' in sco:  f.write(f"    {p}.K = {mfloat(sco['K'])};\n")
                if 'NRADIUS' in sco: f.write(f"    {p}.nradius = {mfloat(sco['NRADIUS'])};\n")
                cs = sorted((int(k[1:]), v) for k, v in sco.items() if re.match(r'^C\d+$', k))
                if cs:
                    idx = ' '.join(str(i) for i,_ in cs)
                    val = ' '.join(mfloat(v) for _,v in cs)
                    f.write(f"    {p}.zrn_C_idx = [{idx}];   % CODE V SCO C-numbers (C1=NRADIUS slot: mode k = C(k+1))\n")
                    f.write(f"    {p}.zrn_C_val = [{val}];\n")
    f.write("end\n")
print("rodgers3_seq.m written")
