function write_report()
%WRITE_REPORT  Assemble r3_report.txt from r3_s0.mat + r3_build.mat.
%   (The committed r3_s0_report.txt is the FROZEN Stage-0 record --
%   this writes a fresh re-run report beside it, never over it.)
%   Pure formatting -- every number comes from the saved run.
    here = fileparts(mfilename('fullpath'));
    addpath(here);
    A = load(fullfile(here,'r3_s0.mat'));    OUT = A.OUT;
    B = load(fullfile(here,'r3_build.mat')); D = B.D;
    S = rodgers3_seq();
    rungs = {'r1','r2','r3','r4','r5'};
    g = OUT.gate_nm;

    f = fopen(fullfile(here,'r3_report.txt'),'w');
    c = onCleanup(@() fclose(f));
    pr = @(varargin) fprintf(f, varargin{:});

    pr('================================================================\n');
    pr(' rodgers3 STAGE 0 -- .seq-truth reproduction of Mike Rodgers''\n');
    pr(' 5-rung WFE ladder (260802-WFOVimager_Offsetfield-jmr)\n');
    pr(' run %s   engine: macos build_release_gfortran; scripts:\n', datestr(now,'yyyy-mm-dd HH:MM'));
    pr(' challenges/rodgers3/build_r3.m + rodgers3.m; truth:\n');
    pr(' rodgers3_seq.m (machine-generated by parse_seq.py).\n');
    pr(' NOTHING IS TUNED TOWARD HIS NUMBERS -- the band is the\n');
    pr(' measurement (rodgers1 rule).\n');
    pr('================================================================\n\n');

    pr('GATE TABLE  (strict RMS WFE per field, nm @ 1000 nm; reference =\n');
    pr('sphere centred on the SPOT CENTROID on the deck-verbatim .seq FPA,\n');
    pr('anchored at the exit pupil, piston-only removal; fields tangent-\n');
    pr('composed; chief of every field aimed through the stop centre by\n');
    pr('real-ray iteration.  "map max" = ceiling of a dense map over the\n');
    pr('full 20x20-deg box -- WHAT HIS NUMBER IS (each pptx slide shows a\n');
    pr('20x20 field map and quotes its ceiling); "9pt" = his .seq\n');
    pr('optimization field points.)\n\n');
    pr('  rung | his nm  | map max  | 9pt max  | 9pt fRMS | map/his | verdict\n');
    pr('  -----+---------+----------+----------+----------+---------+--------\n');
    for k = 1:5
        rk = rungs{k};
        if ~isfield(OUT,rk) || ~OUT.(rk).ran
            pr('   %s  | %7.0f |    --    |    --    |    --    |   --    | NOT RUN\n', rk, g(k));
        else
            o = OUT.(rk);
            pr('   %s  | %7.0f | %8.2f | %8.2f | %8.2f |  %6.3f | %s\n', ...
               rk, g(k), o.gate_stat, o.max_cen, o.frms_cen, o.gate_stat/g(k), pf_(o.pass));
        end
    end
    pr('\n  WHICH STATISTIC HIS NUMBER MATCHES: the MAXIMUM of CODE V''s\n');
    pr('  "RMS WAVEFRONT ERROR vs FIELD ANGLE IN OBJECT SPACE" map over\n');
    pr('  the 20x20-deg box (the slide plots carry the exact metadata --\n');
    pr('  extracted from the embedded EMFs).  His full map statistics\n');
    pr('  (waves @ 1000 nm -> nm):\n\n');
    pr('    rung |    Min   |    Max   |   Avg   |   Std\n');
    his = [ 47.214 158.52  74.356 28.437
           1133.7 8809.6 2557.3 1639.9
             28.081 167.88  77.048 28.195
             19.863 116.72  59.069 19.936
             11.595  53.098 24.722  8.3264];
    for k = 1:5
        pr('     %s  | %8.2f | %8.2f | %7.2f | %7.2f\n', rungs{k}, his(k,:));
    end
    pr('\n  OUR dense-map moments (centroid ref, nm):\n\n');
    pr('    rung |    Min   |    Max   |   Avg   |   Std\n');
    for k = 1:5
        rk = rungs{k};
        if isfield(OUT,rk) && OUT.(rk).ran && ~isempty(OUT.(rk).map_cen)
            m = OUT.(rk).map_cen(:);  m = m(isfinite(m));
            pr('     %s  | %8.2f | %8.2f | %7.2f | %7.2f\n', rk, ...
               min(m), max(m), mean(m), std(m));
        else
            pr('     %s  |    --    |    --    |    --   |    --\n', rk);
        end
    end
    pr('\n  Chief-referenced numbers are stored alongside in r3_s0.mat.\n');

    pr('\n----------------------------------------------------------------\n');
    pr('PER-FIELD STRICT RMS WFE (nm, centroid reference)\n');
    for k = 1:5
        rk = rungs{k};
        if ~isfield(OUT,rk) || ~OUT.(rk).ran, continue; end
        o = OUT.(rk);  R = S.(rk);
        pr('\n  %s -- %s\n', rk, D.(rk).title);
        for q = 1:numel(R.XAN)
            pr('    XAN %+5.1f  YAN %+5.1f : %10.3f nm  (%d rays)\n', ...
               R.XAN(q), R.YAN(q), o.w_cen_nm(q), o.nrays(q));
        end
        pr('    traced gates: centre-field chief lands %.4f mm from the SI\n', norm(o.dSI_mm));
        pr('    origin;  stop footprint centre [%+.3f %+.3f] mm, max radius\n', o.fp_stop_mm(1:2));
        pr('    %.3f mm vs paraxial stop semi-diam %.3f mm.\n', o.fp_stop_mm(3:4));
        if ~isempty(o.map_cen)
            [mx,im] = max(o.map_cen(:));
            xg = linspace(-10,10,o.map_n); yg = linspace(R.YAN(2)-10,R.YAN(2)+10,o.map_n);
            [XG,YG] = meshgrid(xg,yg);
            pr('    dense %dx%d map: max %.2f nm at XAN %+.1f YAN %+.1f (chief-ref max %.2f)\n', ...
               o.map_n, o.map_n, mx, XG(im), YG(im), max(o.map_chf(:)));
        end
    end

    pr('\n----------------------------------------------------------------\n');
    pr('CONVENTION DECISIONS TAKEN (all engine-truth-verified or gated)\n\n');
    pr('1. LAYOUT: one global frame, metres, beam enters +z; signed CODE V\n');
    pr('   thicknesses accumulated directly (m1 %+0.6f, stop/m2 %+0.6f,\n', ...
       D.r1.z_m1, D.r1.z_stop);
    pr('   m3 %+0.6f m).  KrElt = signed CODE V radius (m), KcElt = K\n', D.r1.z_m3);
    pr('   verbatim, psiElt (0,0,-1)-style (rodgers1 emission precedent).\n\n');
    pr('2. ASPHERES: engine truth read from surfsub.F AsphSrf BEFORE first\n');
    pr('   use: AsphCoef(i) multiplies h^(2i+2) of sag along +psiElt\n');
    pr('   (fh = sum coef(i)*h^(2i+2); zc = rho - fh*psi).  CODE V ASP\n');
    pr('   A,B,C multiply r^4,r^6,r^8 of sag along local +z = -psiElt,\n');
    pr('   so AsphCoef = -ASP * (1e9, 1e15, 1e21) [mm->m units].\n');
    pr('   Gated by r1 jointly with the geometry.\n\n');
    pr('3. FIELDS: CODE V XAN/YAN tangent-composed,\n');
    pr('   dir = [tand(XAN), tand(YAN), 1]/norm.  Gated by r1 (+/-10 deg\n');
    pr('   box) and r2-r5 (22 deg offset).\n\n');
    pr('4. SOURCE/PUPIL MODEL: collimated bundle, diameter = EPD 75 mm,\n');
    pr('   perpendicular to each field''s chief; chief aimed through the\n');
    pr('   stop centre (on the m2 plane) by real-ray Newton iteration --\n');
    pr('   CODE V aims reference rays at the stop.  The deck carries NO\n');
    pr('   ApStop= line ON PURPOSE: the engine keyword triggers\n');
    pr('   STRAIGHT-LINE source aiming through StopPos (srcaim.inc), which\n');
    pr('   is wrong for a stop that sits after one reflection (it also\n');
    pr('   freezes ChfRayPos, discovered as a singular aiming Jacobian).\n\n');
    pr('5. YDE/ADE SIGN MAP -- MEASURED by an 8-configuration screen\n');
    pr('   (probe_cfg.m; acceptance = geometry, never WFE-tuning), and it\n');
    pr('   REFUTES the NOTES item-3 odd/even reflection-parity rule:\n');
    pr('     * ALL YDE VERBATIM (one global frame, no reflection parity,\n');
    pr('       stop plane included),\n');
    pr('     * ALL ADE sense-flipped uniformly: alpha_macos = -ADE_codev\n');
    pr('       in alpha = atan2d(psi_y, -psi_z)\n');
    pr('   == exactly the rodgers1 empirical decode (convention_decode.m:\n');
    pr('   YDE verbatim, ADE opposite sense, no parity).  Evidence chain:\n');
    pr('   (a) the notes map {stop -, rec -YDE/-ADE} misses the SI origin\n');
    pr('       by 219.6 mm = 2x recenter YDE (ladder_notesparity_FAIL.log);\n');
    pr('   (b) recenter-ADE sign pinned by an origin discriminant\n');
    pr('       (flipped sense ~0.0001 mm miss, verbatim ~7.1 mm);\n');
    pr('   (c) of 8 {stop, recY, recA} sign sets, TWO are origin-\n');
    pr('       admissible; the all-verbatim-YDE one reproduces his map''s\n');
    pr('       shape (rows 12/22/32 = 2.81/2.56/7.38 waves vs his\n');
    pr('       min 1.13 / avg 2.56 / max 8.81) and a physical m3 patch\n');
    pr('       (~110-160 mm, inside r5''s m3 NRADIUS 326.5); the other\n');
    pr('       ({stop flipped}) gives a FLAT map (3.1-4.0 waves) and an\n');
    pr('       m3 chief patch at +372 mm -- outside his own m3 aperture.\n');
    pr('   Rotations are about the decentered vertex (CODE V: decenter\n');
    pr('   first, then tilt).\n\n');
    pr('6. ZERNIKE (r5): engine truth from surfsub.F FreeFormSrf (line\n');
    pr('   ~2174): Mon/Zernike sag is applied along +zMon, NOT psi; the\n');
    pr('   polynomial (x,y) come from xMon/yMon/lMon.  The deck therefore\n');
    pr('   carries the CODE V local surface frame directly (zMon = local\n');
    pr('   +z, xMon = +x, yMon = local +y, all tilted with the mirror) and\n');
    pr('   the SCO coefficients go in VERBATIM (*1e-3 mm->m), no sign flip.\n');
    pr('   ZernType= BornWolf == CODE V standard Zernike TERM-FOR-TERM\n');
    pr('   (surfsub.F ZerntoMon2 table: 2 = R cos(theta) x-tilt, 5 = power,\n');
    pr('   13 = spherical); macos mode = deck zrn_C_idx - 1 (C1 = NRADIUS\n');
    pr('   slot); C2 -> mode 1 = PISTON, real content, CARRIED.\n');
    pr('   lMon = NRADIUS*1e-3.  Surface shape data do NOT get the parity\n');
    pr('   flip (radii signs do not alternate; neither do ASP/ZRN terms).\n\n');
    pr('7. WFE STATISTIC + REFERENCE: per-field strict RMS WFE = std of\n');
    pr('   exact OPL to a reference sphere centred on the spot centroid on\n');
    pr('   the frozen deck FPA (Dave 2026-07-31 centroid ruling), anchored\n');
    pr('   at the exit pupil (crossing of two aimed chiefs = stop image),\n');
    pr('   piston-only removal (design/src strict_refs kernel).  His\n');
    pr('   ladder number = ceiling of the 20x20-deg field MAP (dense max),\n');
    pr('   NOT the max over the 9 .seq optimization points.\n');

    pr('\n----------------------------------------------------------------\n');
    pr('CAVEATS / HONEST LIMITS\n');
    pr('* Pupil sampling: uniform circular grid (nGridpts=41, ~1184 rays)\n');
    pr('  perpendicular to the chief, diameter 75 mm at every field; CODE V\n');
    pr('  grids the STOP uniformly, so our off-axis pupil patch differs by\n');
    pr('  the footprint ellipticity (~cos 22 deg in y) and real-ray pupil\n');
    pr('  distortion.  r1 footprint check: traced max radius vs paraxial\n');
    pr('  stop semi-diameter agree to ~0.2%%.\n');
    pr('* Object at 1.15e10 mm treated as collimated (focus-shift proxy\n');
    pr('  well below the solved image defocus, rodgers1 precedent).\n');
    pr('* Map MINIMA on r2 (ours 1889 vs his 1134 nm) and r4 (28.9 vs\n');
    pr('  19.9 nm) sit above his; maxima, averages and std track (r1/r3/r5\n');
    pr('  moments all within ~10%%).  The low end is where the pupil-model\n');
    pr('  difference (uniform perpendicular-to-chief bundle vs CODE V''s\n');
    pr('  stop-gridded rays) and the reference-sphere radius anchor matter\n');
    pr('  most relative to the small residual -- a known, bounded\n');
    pr('  approximation, NOT a convention error (the gated statistic is\n');
    pr('  the map maximum).\n');
    pr('* Band rule: PASS = dense-map max within [0.8, 1.25]x of his\n');
    pr('  number; the residual ratio is reported, never tuned.\n');

    pr('\nARTIFACTS\n');
    pr('  challenges/rodgers3: build_r3.m, rodgers3.m, write_report.m,\n');
    pr('  parse_seq.py + the five TML_*.seq (truth source),\n');
    pr('  r3_r1.in .. r3_r5.in, r3_build.mat, r3_s0.mat,\n');
    pr('  r3_s0_report.txt (the frozen Stage-0 record),\n');
    pr('  r3_report.txt (this file).  Stage-0 probe scripts + FAIL logs\n');
    pr('  remain in the sandbox record ~/dev/MACOS_sandbox/Design/Rodgers3/s0.\n');
    fprintf('wrote r3_report.txt\n');
end

function s = pf_(p), if p, s='PASS'; else, s='FAIL'; end, end
function v = getor_(O, rk, fld, d)
    if isfield(O,rk) && isfield(O.(rk),fld) && O.(rk).ran, v = O.(rk).(fld); else, v = d; end
end
