function OUT = tma_longslit_1k5(stages, resume_upto)
%TMA_LONGSLIT_1K5  The template at the dyson5 1.5k spec (CC / Dave 2026-10-08): the 3k recipe, one method for both.
%   Strip +-2.35 deg onto a 27 mm slit (1500 px), f 330 / D 183 / F/1.8, the same Fig. 4b seed legs and incidences, the
%   same row sets as the 3k deck of record (TELE, CONE, OFF x1000, along-slit spot x3, outer fields 1/1/2/3/3, BOW and
%   CBOW).  Ladder: conic -> ASPHERE (the 1.5k may not need freeform) -> pole-frame freeform degree 3-4 -> 3-6.  E2E
%   through the 130 mm silica Dyson of record (size:D:130, its join template, the 1500 px strip) under both launches,
%   rolls 0 / 180.  Records tag 'tls1k5' (the 3k default 'tls' is untouched).
if nargin < 1, stages = {'first_order', 'section', 'figure', 'e2e'}; end
if nargin < 2, resume_upto = -1; end
W = struct('w_spot_x', 3, 'field_wt', [1 1 2 3 3], 'w_off', 1000);
% R5 ffc (2026-10-08): R4 reached the pixel floor at -0.3 mm of clearance (the M3 -> slit leg into M2's body); ffc is R4
% continued with the CLEAR wall (tls_figure: the record's clearance rule every iteration), target 2 mm
L = struct('name', {'conic', 'asph', 'ff34', 'ff', 'ffc'}, ...
           'dofs', {{'theta', 'slit_dz'}, {'theta', 'slit_dz', 'asph'}, {'theta', 'slit_dz', 'mon34'}, {'theta', 'slit_dz', 'mon'}, ...
                    {'theta', 'slit_dz', 'mon'}}, ...
           'from', {0, 1, 1, 3, 4}, 'maxfev', {1500, 1500, 3000, 3000, 1500}, ...
           'w_spot_x', {W.w_spot_x, W.w_spot_x, W.w_spot_x, W.w_spot_x, W.w_spot_x}, ...
           'field_wt', {W.field_wt, W.field_wt, W.field_wt, W.field_wt, W.field_wt}, ...
           'w_tel', {[], [], [], [], []}, 'w_off', {W.w_off, W.w_off, W.w_off, W.w_off, W.w_off}, ...
           'w_clear', {[], [], [], [], 3000});
over = struct('tag', 'tls1k5', 'strip_half_deg', 2.35, 'slit_m', 0.027, 'ladder', L, ...
              'e2e', struct('tel_dyson', 'size:D:130', 'template', 'dyson5_t5e_tA_EP_pz_m30_B1_e2e.in', 'tel_npix_xt', 1500), ...
              'e2e_roll_deg', [0 180], 'resume_upto', resume_upto);
OUT = tma_longslit_run(stages, over);
end
