function perts = spectrometer_sens_defaults(G, opts)
%SPECTROMETER_SENS_DEFAULTS  The addendum-49 tolerance list for a Dyson deck (spectrometer_rx emission).
%   perts = spectrometer_sens_defaults(G) -- one perturbation per row, the element groups by EltName:
%     lens   = BlockFaceIn, BlockSphereOut, BlockSphereIn, BlockFaceOut (one rigid part, both passes),
%              pivot the slit face (BlockFaceIn's vertex);
%     grating = Grating, pivot its vertex;  detector = PreFPA + FPA, pivot the FPA vertex;  slit = the launch.
%   Amounts (addendum 49): decenter 10 um, tilt 10 urad, dR/R 1e-4, dn 1e-5, thickness 10 um; grating period
%   d(1/d)/(1/d) 1e-5 and clocking 10 urad; slit 10 um along / across / defocus; detector defocus 10 um, tilt
%   10 urad; the lens-to-grating air space 10 um.  The lens index row needs the glass's Sellmeier coefficients
%   (opts.sellmeier, Schott form [B1 B2 B3 C1 C2 C3], C in um^2; default CaF2 as in the engine's built-in table)
%   and the wavelength where dn is exact (opts.lambda0_m, default the chain's centre wavelength).
arguments
    G struct
    opts.sellmeier (1,6) double = [0.5675888 0.4710914 3.8484723 0.0025264299876 0.010078332803 1200.5559729]
    opts.lambda0_m (1,1) double = NaN
end
if isnan(opts.lambda0_m), opts.lambda0_m = G.src.lambda_c; end
lens = {'BlockFaceIn', 'BlockSphereOut', 'BlockSphereIn', 'BlockFaceOut'};  sph = {'BlockSphereOut', 'BlockSphereIn'};
glass = {'BlockFaceIn', 'BlockSphereIn'};      % the elements whose IndRef is the glass (into the block, both passes)
gr = {'Grating'};  det = {'PreFPA', 'FPA'};
mk = @(name, kind, elts, amount, unit, pivot) struct('name', name, 'kind', kind, 'elts', {elts}, 'amount', amount, ...
     'unit', unit, 'pivot', pivot, 'sellmeier', opts.sellmeier, 'lambda0_m', opts.lambda0_m);
perts = [ ...
    mk('lens_decenter_x', 'decenter_x', lens, 10e-6, 'm', 'BlockFaceIn'), ...
    mk('lens_decenter_y', 'decenter_y', lens, 10e-6, 'm', 'BlockFaceIn'), ...
    mk('lens_tilt_x', 'tilt_x', lens, 10e-6, 'rad', 'BlockFaceIn'), ...
    mk('lens_tilt_y', 'tilt_y', lens, 10e-6, 'rad', 'BlockFaceIn'), ...
    mk('lens_radius', 'radius', sph, 1e-4, 'dR/R', ''), ...
    mk('lens_index', 'index', glass, 1e-5, 'dn', ''), ...
    mk('lens_thickness', 'thickness', sph, 10e-6, 'm', 'BlockSphereOut'), ...
    mk('grating_decenter_x', 'decenter_x', gr, 10e-6, 'm', 'Grating'), ...
    mk('grating_decenter_y', 'decenter_y', gr, 10e-6, 'm', 'Grating'), ...
    mk('grating_tilt_x', 'tilt_x', gr, 10e-6, 'rad', 'Grating'), ...
    mk('grating_tilt_y', 'tilt_y', gr, 10e-6, 'rad', 'Grating'), ...
    mk('grating_radius', 'radius', gr, 1e-4, 'dR/R', ''), ...
    mk('grating_period', 'period', gr, 1e-5, 'd(1/d)/(1/d)', ''), ...
    mk('grating_clock', 'clock', gr, 10e-6, 'rad', 'Grating'), ...
    mk('air_space', 'despace', gr, 10e-6, 'm', 'Grating'), ...
    mk('slit_x', 'slit_x', {}, 10e-6, 'm', ''), ...
    mk('slit_y', 'slit_y', {}, 10e-6, 'm', ''), ...
    mk('slit_defocus', 'slit_z', {}, 10e-6, 'm', ''), ...
    mk('detector_defocus', 'despace', det, 10e-6, 'm', 'FPA'), ...
    mk('detector_tilt_x', 'tilt_x', det, 10e-6, 'rad', 'FPA'), ...
    mk('detector_tilt_y', 'tilt_y', det, 10e-6, 'rad', 'FPA')];
end
