function R = spectrometer_slit_loss(P, file, opts)
%SPECTROMETER_SLIT_LOSS  The slit-width diffraction loss, measured vs sinc^2.
%   R = spectrometer_slit_loss(P, file) builds a mini deck -- a collimated
%   beam through a RECTANGULAR aperture of the slit width w = P.slit_px *
%   pixel (long axis P.slit_len along x), then a far-field leg to the grating
%   plane at distance z = P.z_grating (a flat Return of radius 1e22 at the
%   slit, PropType FarField, zElt = z, the Grating_example idiom) -- and
%   measures the fraction of the propagated energy that lands inside the
%   grating's acceptance, |y| <= z tan(u), u = asin(1/(2 F)), per wavelength.
%   The closed form it is held to: the energy of sinc^2(w sin(theta)/lambda)
%   inside |sin(theta)| <= 1/(2F) -- the along-slit direction carries no
%   loss (the slit is long).  Both are stated per lambda; the difference is
%   the finite-grid / Fresnel-kernel residual.
%
%   Conventions: the slit is illuminated uniformly (the telescope's F/# cone
%   is not modelled -- that is the full partially-coherent calculation the
%   paper puts at ~10 %); FPA frame = global X/Y; far-field pitch
%   lambda z/(N dx_in) and the window lambda z/dx_in -- INDEPENDENT of N --
%   so the modelled slit length (= the beam Aperture = N_grid dx_in) is
%   kept SHORT (0.15 mm: dx_in 0.6 um resolves the 36 um slit by 60
%   samples and the window at 380 nm is 450 mm, covering the +-195 mm
%   acceptance); the short slit's own x-diffraction (2.5 mrad) is
%   integrated over and does not enter the y loss.
%   Returns R.lams, R.loss_engine, R.loss_sinc, R.window_m, R.dx_m.
    arguments
        P struct
        file (1,:) char
        opts.lams (1,:) double = [380e-9 700e-9 1440e-9 2500e-9]
        opts.model (1,1) double = 1024
        opts.ngridpts (1,1) double = 255
        opts.slit_len (1,1) double = 0.15e-3
        opts.z_grating (1,1) double = 0.7
    end
    w = P.slit_px*P.pixel_m;  z = opts.z_grating;  u = asin(1/(2*P.Fno));  ymax = z*tan(u);
    ap = opts.slit_len;   % beam (and grid) width along x; the slit is the aperture
    F = @(v) sprintf('%.15G  %.15G  %.15G', v(1), v(2), v(3));
    ln = {};
    ln{end+1} = '% slit-loss mini deck -- generated by spectrometer_slit_loss';
    ln{end+1} = sprintf('        ChfRayDir=  %s', F([0 0 1]));
    ln{end+1} = sprintf('        ChfRayPos=  %s', F([0 0 -0.01]));
    ln{end+1} = '          zSource=  1.0D+22';
    ln{end+1} = '        BaseUnits=  m';   ln{end+1} = '        WaveUnits=  m';
    ln{end+1} = '           IndRef=  1.0D+00';  ln{end+1} = '           Extinc=  0.0D+00';
    ln{end+1} = sprintf('          Wavelen=  %.9E', opts.lams(1));
    ln{end+1} = '             Flux=  1.0D+00';
    ln{end+1} = sprintf('         Aperture=  %.9E', ap);
    ln{end+1} = '         Obscratn=  0.0D+00';  ln{end+1} = '         GridType=  Square';
    ln{end+1} = sprintf('         nGridpts=  %d', opts.ngridpts);
    ln{end+1} = sprintf('            xGrid=  %s', F([1 0 0]));  ln{end+1} = sprintf('            yGrid=  %s', F([0 1 0]));
    ln{end+1} = '             nElt=  4';
    blk = @(k, name, elt, kr, psi, vpt, ap, prop, zelt) {sprintf('             iElt=  %d', k), sprintf('          EltName=  %s', name), ...
        sprintf('          Element=  %s', elt), '          Surface=  Flat', sprintf('            KrElt=  %.6E', kr), '            KcElt=  0', ...
        sprintf('           psiElt=  %s', F(psi)), sprintf('           VptElt=  %s', F(vpt)), sprintf('           RptElt=  %s', F(vpt)), ...
        '           IndRef=  1.0D+00', '           Extinc=  0.0D+00', '            nCoat=  0', sprintf('             xObs=  %s', F([1 0 0])), '             nObs=  0', ap{:}, ...
        sprintf('         PropType=  %s', prop), sprintf('             zElt=  %.9E', zelt), '          nECoord= -6'};
    apr = {'           ApType=  Rectangular', sprintf('            ApVec=  %.9E  %.9E  %.9E  %.9E', -ap/2, ap/2, -w/2, w/2)};
    % the aperture sits 1 mm BEFORE the Return plane: coincident elements leave
    % a zero path and the engine drops the rays
    % the Rx_Cass_FarField sandwich: a Return REVERSES the beam, so the field
    % is carried forward to the grating plane, reversed there, run back to a
    % flat reference at the slit plane (the first physical-optics element,
    % where the grid is seeded from the slit-masked rays) and far-field
    % propagated forward over z to the grating plane
    ln = [ln, blk(1, 'Slit', 'Obscuring', -1e22, [0 0 -1], [0 0 -1e-3], apr, 'Geometric', 1e22)];
    ln = [ln, blk(2, 'GratingReturn', 'Return', -1e22, [0 0 1], [0 0 z], {'           ApType=  None'}, 'Geometric', 1e22)];
    ln = [ln, blk(3, 'SlitPlane', 'Return', -1e22, [0 0 1], [0 0 0], {'           ApType=  None'}, 'FarField', z)];
    ln = [ln, blk(4, 'GratingPlane', 'FocalPlane', -1e22, [0 0 1], [0 0 z], {'           ApType=  None'}, 'Geometric', 1e22)];
    ln{end+1} = '';  ln{end+1} = '         nOutCord=  5';
    ln{end+1} = '             Tout=  1.0D+00  0.0D+00  0.0D+00  0.0D+00  0.0D+00  0.0D+00  0.0D+00';
    ln{end+1} = '                    0.0D+00  1.0D+00  0.0D+00  0.0D+00  0.0D+00  0.0D+00  0.0D+00';
    ln{end+1} = '                    0.0D+00  0.0D+00  0.0D+00  1.0D+00  0.0D+00  0.0D+00  0.0D+00';
    ln{end+1} = '                    0.0D+00  0.0D+00  0.0D+00  0.0D+00  1.0D+00  0.0D+00  0.0D+00';
    ln{end+1} = '                    0.0D+00  0.0D+00  0.0D+00  0.0D+00  0.0D+00  0.0D+00  1.0D+00';
    fid = fopen(file, 'w');  fprintf(fid, '%s\n', ln{:});  fclose(fid);
    macos.init(opts.model);  macos.load_rx(file);
    nl = numel(opts.lams);  R.lams = opts.lams;  R.loss_engine = nan(1, nl);  R.loss_sinc = nan(1, nl);  R.dx_m = nan(1, nl);  R.window_m = nan(1, nl);
    for j = 1:nl
        lam = opts.lams(j);  macos.set_src_wvl(lam);  macos.modify();
        I = macos.intensity(4);  dx = macos.dx_at(4);  N = size(I, 1);  c0 = N/2 + 1;
        R.energy(j) = sum(I(:));
        g = ((1:N) - c0)*dx;  [~, jj] = ndgrid(1:N, 1:N);  yv = ((jj - c0)*dx);
        R.dx_m(j) = dx;  R.window_m(j) = N*dx;
        R.loss_engine(j) = 1 - sum(I(abs(yv) <= ymax))/sum(I(:));
        % closed form: sinc^2 energy outside |sin theta| <= 1/(2F)
        s = linspace(-1, 1, 200001);  E = sinc(w*s/lam).^2;
        R.loss_sinc(j) = 1 - trapz(s(abs(s) <= 1/(2*P.Fno)), E(abs(s) <= 1/(2*P.Fno)))/trapz(s, E);
        R.inside_window(j) = (ymax <= R.window_m(j)/2);
    end
    R.w_m = w;  R.z_m = z;  R.ymax_m = ymax;  R.deck = file;
end
