load('afocal4_edge140.mat','R');
T = R.rows;
fprintf('\n  BOTH FRAMES, side by side (um)\n');
fprintf('%-27s %10s %10s %10s %10s\n','design','wander','wander','edgecen','edgecen');
fprintf('%-27s %10s %10s %10s %10s\n','','REFIT','placed','REFIT','placed');
fprintf('%s\n',repmat('-',1,72));
for i = 1:numel(T)
    fprintf('%-27s %10.1f %10.1f %10.1f %10.1f\n', T(i).name, ...
        T(i).wander_full_um, T(i).wander_placed_um, ...
        T(i).cen_rms_um, T(i).cen_placed_um);
end
i3 = find(strcmp({T.name},'3-mir, tilt/dec (the 469)'),1);
i4 = find(strcmp({T.name},'4-mir, rung 4 (the 157)'),1);
fprintf('\n  wander ratio 3-mir/4-mir:  REFIT %.2fx   placed %.2fx\n', ...
    T(i3).wander_full_um/T(i4).wander_full_um, ...
    T(i3).wander_placed_um/T(i4).wander_placed_um);
fprintf('  4-mir frame gap (placed/refit): wander %.2fx   edge centroid %.2fx\n', ...
    T(i4).wander_placed_um/T(i4).wander_full_um, ...
    T(i4).cen_placed_um/T(i4).cen_rms_um);
fprintf('  3-mir frame gap (placed/refit): wander %.2fx   edge centroid %.2fx\n', ...
    T(i3).wander_placed_um/T(i3).wander_full_um, ...
    T(i3).cen_placed_um/T(i3).cen_rms_um);
