classdef tProperCompareCoroPhase3 < matlab.unittest.TestCase
%TPROPERCOMPARECOROPHASE3  Port of pymacos test_coro_nfprop_phase3.py.
%   6 tests covering the rest of the Rx_Coro optical chain:
%     3a NFPlane Elt 5 -> 6      (post-DM NF prop, sum-norm <1e-7)
%     3b sphere->plane 8 -> 9    (focal mask plane, peak-norm <0.1)
%     4a pupil->pupil 8 -> 10    (through-focus to far pupil, sum-norm <1e-4)
%     4b NFPlane 13 -> 14        (post-focus NF, noLyot, sum-norm <5e-4)
%     5.1 ExitPupil -> SciFP no mask  (peak-norm <1e-4)
%     5.2 ExitPupil -> SciFP w/ FPM   (peak-norm <1e-5)
%
%   All at model_size = 1024 — runs in the size=1024 group of
%   run_mmacos_tests.sh.

    properties
        results_dir
    end

    methods (TestClassSetup)
        function setupClass(testCase)
            assert(exist('prop_begin', 'file') == 2, ...
                ['PROPER MATLAB not on path; add ~/dev/proper_matlab/' ...
                 ' via addpath or run via run_mmacos_tests.sh.']);
            testCase.results_dir = fullfile(fileparts( ...
                mfilename('fullpath')), 'results', 'phase3');
        end
    end

    methods (Test)
        % --- 3a: NFPlane Elt 5 -> Elt 6 -----------------------------
        function test_coro_nfplane_elt5_to_elt6(testCase)
            geom = geometries.coro_nfprop('src_elt', 5, 'detector_elt', 6);
            [im, dx_m, wf] = macos_run_coro_nfprop(geom);
            [ip, dx_p]     = proper_run_coro_nfprop(geom, wf);

            testCase.verifyEqual(size(im), size(ip));
            testCase.verifyEqual(dx_p, dx_m, 'RelTol', 1e-3);

            m = compare_and_record('coro_nfplane_elt5_to_elt6', ...
                im, ip, dx_m, ...
                'norm_kind', 'sum', ...
                'crop_pixels', size(im, 1), ...
                'results_dir', testCase.results_dir);
            fprintf(['  3a Elt 5->6 NF: max=%.3e rms=%.3e ' ...
                     'Δcom=(%+d,%+d) px\n'], ...
                m.max_abs, m.rms_abs, m.dx_pix, m.dy_pix);
            testCase.verifyLessThan(m.max_abs, 1e-7, sprintf( ...
                'max |a-b| = %.3e sum-norm > 1e-7', m.max_abs));
            testCase.verifyLessThan(m.rms_abs, 1e-8, sprintf( ...
                'RMS |a-b| = %.3e sum-norm > 1e-8', m.rms_abs));
        end

        % --- 3b: Sphere->plane Elt 8 -> Elt 9 -----------------------
        function test_coro_sphere_to_plane_elt8_to_elt9(testCase)
            geom = geometries.coro_sphere_to_plane();
            [im, dx_m, wf] = macos_run_sphere_to_plane(geom);
            [ip, dx_p]     = proper_run_sphere_to_plane(geom, wf);

            testCase.verifyEqual(size(im), size(ip));
            testCase.verifyEqual(dx_p, dx_m, 'RelTol', 1e-3);

            m = compare_and_record('coro_sphere_to_plane_elt8_to_elt9', ...
                im, ip, dx_m, ...
                'norm_kind', 'peak', ...
                'crop_pixels', size(im, 1), ...
                'results_dir', testCase.results_dir);
            fprintf(['  3b Elt 8->9 sphere: max=%.3e rms=%.3e ' ...
                     'Δcom=(%+d,%+d) px\n'], ...
                m.max_abs, m.rms_abs, m.dx_pix, m.dy_pix);
            testCase.verifyLessThan(m.max_abs, 0.1, sprintf( ...
                'max |a-b| = %.3e peak-norm > 0.1', m.max_abs));
        end

        % --- 4a: Pupil->pupil through focus, Elt 8 -> 10 ------------
        function test_coro_pupil_to_pupil_elt8_to_elt10(testCase)
            geom = geometries.coro_pupil_to_pupil();
            [im, dx_m, wf] = macos_run_pupil_to_pupil(geom);
            [ip, dx_p]     = proper_run_pupil_to_pupil(geom, wf);

            testCase.verifyEqual(size(im), size(ip));
            testCase.verifyEqual(dx_p, dx_m, 'RelTol', 1e-3);

            m = compare_and_record('coro_pupil_to_pupil_elt8_to_elt10', ...
                im, ip, dx_m, ...
                'norm_kind', 'sum', ...
                'crop_pixels', size(im, 1), ...
                'results_dir', testCase.results_dir);
            fprintf(['  4a Elt 8->10 pupil-pupil: max=%.3e rms=%.3e ' ...
                     'Δcom=(%+d,%+d) px\n'], ...
                m.max_abs, m.rms_abs, m.dx_pix, m.dy_pix);
            testCase.verifyLessThan(m.max_abs, 1e-4, sprintf( ...
                'max |a-b| = %.3e sum-norm > 1e-4', m.max_abs));
        end

        % --- 4b: NFPlane Elt 13 -> 14, no Lyot ----------------------
        function test_coro_nfplane_elt13_to_elt14(testCase)
            geom = geometries.coro_nfprop( ...
                'rx_filename',  'Rx_Coro_noLyot.in', ...
                'src_elt',      13, ...
                'detector_elt', 14);
            [im, dx_m, wf] = macos_run_coro_nfprop(geom);
            [ip, dx_p]     = proper_run_coro_nfprop(geom, wf);

            testCase.verifyEqual(size(im), size(ip));
            testCase.verifyEqual(dx_p, dx_m, 'RelTol', 1e-3);

            m = compare_and_record('coro_nfplane_elt13_to_elt14', ...
                im, ip, dx_m, ...
                'norm_kind', 'sum', ...
                'crop_pixels', size(im, 1), ...
                'results_dir', testCase.results_dir);
            fprintf(['  4b Elt 13->14 NF: max=%.3e rms=%.3e ' ...
                     'Δcom=(%+d,%+d) px\n'], ...
                m.max_abs, m.rms_abs, m.dx_pix, m.dy_pix);
            testCase.verifyLessThan(m.max_abs, 5e-4, sprintf( ...
                'max |a-b| = %.3e sum-norm > 5e-4', m.max_abs));
            testCase.verifyLessThan(m.rms_abs, 1e-5, sprintf( ...
                'RMS |a-b| = %.3e sum-norm > 1e-5', m.rms_abs));
        end

        % --- 5.1: ExitPupil Elt 20 -> SciFP Elt 21, no mask ---------
        function test_coro_exit_pupil_to_focal_no_mask(testCase)
            geom = geometries.coro_sphere_to_plane( ...
                'rx_filename',    'Rx_Coro_noLyot.in', ...
                'src_elt',        20, ...
                'detector_elt',   21, ...
                'focal_length_m', 0.9514);
            [im, dx_m, wf] = macos_run_sphere_to_plane(geom);
            [ip, dx_p]     = proper_run_sphere_to_plane(geom, wf);

            testCase.verifyEqual(size(im), size(ip));
            testCase.verifyEqual(dx_p, dx_m, 'RelTol', 1e-3);

            m = compare_and_record('coro_exit_pupil_to_focal_no_mask', ...
                im, ip, dx_m, ...
                'norm_kind', 'peak', ...
                'crop_pixels', size(im, 1), ...
                'results_dir', testCase.results_dir);
            fprintf(['  5.1 Elt 20->21 no mask: max=%.3e rms=%.3e ' ...
                     'Δcom=(%+d,%+d) px\n'], ...
                m.max_abs, m.rms_abs, m.dx_pix, m.dy_pix);
            testCase.verifyLessThan(m.max_abs, 1e-4, sprintf( ...
                'max |a-b| = %.3e peak-norm > 1e-4', m.max_abs));
        end

        % --- 5.2: ExitPupil Elt 20 -> SciFP Elt 21, FPM + Lyot ------
        function test_coro_exit_pupil_to_focal_with_mask(testCase)
            geom = geometries.coro_sphere_to_plane( ...
                'rx_filename',    'Rx_Coro_FPM.in', ...
                'src_elt',        20, ...
                'detector_elt',   21, ...
                'focal_length_m', 0.9514);
            [im, dx_m, wf] = macos_run_sphere_to_plane(geom);
            [ip, dx_p]     = proper_run_sphere_to_plane(geom, wf);

            testCase.verifyEqual(size(im), size(ip));
            testCase.verifyEqual(dx_p, dx_m, 'RelTol', 1e-3);

            m = compare_and_record('coro_exit_pupil_to_focal_with_mask', ...
                im, ip, dx_m, ...
                'norm_kind', 'peak', ...
                'crop_pixels', size(im, 1), ...
                'results_dir', testCase.results_dir);
            fprintf(['  5.2 Elt 20->21 FPM+Lyot: max=%.3e rms=%.3e ' ...
                     'Δcom=(%+d,%+d) px\n'], ...
                m.max_abs, m.rms_abs, m.dx_pix, m.dy_pix);
            testCase.verifyLessThan(m.max_abs, 1e-5, sprintf( ...
                'max |a-b| = %.3e peak-norm > 1e-5', m.max_abs));
        end
    end
end
