% t5-unguided: one documented call, per oi_story's own help text.
tdir = '/home/dcr/dev/MACOS_res_dev/mmacos/templates/10_telescopes/offset_imager';
run('/home/dcr/dev/MACOS_res_dev/mmacos/mmacos_setup.m');
addpath(tdir);                       % README's "Run it" recipe did not do this

fprintf('T5 START %s\n', datestr(now,'yyyy-mm-dd HH:MM:SS'));
t0 = tic;

OUT = oi_story(struct( ...
    'name','t5-unguided', 'tag','t5', ...
    'outdir', fullfile(tdir,'t5_unguided','attempt2'), ...
    'EPD_m', 0.150, 'Fno', 3.3, 'lambda_m', 1.0e-6, ...
    'box_deg', [15 15], 'offset_deg', 22.5, ...
    'exit_dir', [0 0 -1], 'exit_tol_deg', 0.1, ...
    'clear_m', [0.040 0.025], ...
    'z_m1_m', 1.09717872, ...
    'spacings_m', [-1.19277972 0 1.2223662], ...
    'seed_R1_m', 14.52, ...
    'gn_iters', 30));

fprintf('T5 DONE  %s  (%.1f min)\n', datestr(now,'yyyy-mm-dd HH:MM:SS'), toc(t0)/60);
save(fullfile(tdir,'t5_unguided','attempt2','t5_story.mat'),'OUT','-v7.3');
