
% replay.m -- this sript runs through the sensitivities generated by GMI to
% provide a quick visual check that they all make sense.

% Files associated with test_gmi_ff.m: call_GMI.m; ff_pie.in; flat.txt; 
% GMI.mexa64; gmi_Init_ff.m; grfont.dat; macos_glass_list.txt; 
% macos_param.txt; test_gmi_ff.m; ff_pie_dwdx_urad_um.mat; 
% ff_pie_dwdz_urad_um.mat; OPDMask_g.mat; 

load ff_pie_dwdx_urad_um.mat
load ff_pie_dwdz_urad_um.mat

[nw,nx] = size(dwdx)
nz = size(dwdz,2)

% Plot dwdx

figure(1), clf
for ii=1:nx
    opd = v2m(dwdx(:,ii),ix);
    mimg(opd,1)
    title('dwdx, DOF # ', num2str(ii))
    pause(0.1)
end

figure(2), clf
for ii=1:nz
    opd = v2m(dwdz(:,ii),ix);
    mimg(opd,1)
    title('dwdz, DOF # ', num2str(ii))
    pause(0.1)
end